name: Generate Build Matrix
description: Generate build matrix for a platform (handles checkout and matrix generation)

inputs:
  platform:
    description: 'Platform (linux, windows, macos, android, ios)'
    required: true
  build-type:
    description: 'Build type override'
    required: false
    default: ''

outputs:
  matrix:
    description: 'Build matrix JSON'
    value: ${{ steps.matrix.outputs.matrix }}
  timeout_minutes:
    description: 'Timeout in minutes'
    value: ${{ steps.matrix.outputs.timeout_minutes }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        sparse-checkout: |
          .github/actions
          .github/scripts
          .github/build-config.json
        sparse-checkout-cone-mode: false

    - name: Generate Matrix
      id: matrix
      uses: ./.github/actions/matrix-generator
      with:
        platform: ${{ inputs.platform }}
        build-type: ${{ inputs.build-type }}
