#pragma once

#include "UnitTest.h"

class GStreamerTest : public UnitTest
{
    Q_OBJECT

private slots:
    void init() override;

    void _testIsValidRtspUri();
    void _testIsHardwareDecoderFactory();
    void _testSetCodecPrioritiesDefault();
    void _testSetCodecPrioritiesDefaultPrefersMatchingD3DDecoder();
    void _testSetCodecPrioritiesSkipsAbsentD3DDecoders();
    void _testD3D12RhiDisablesGpuZeroCopySink();
    void _testSetCodecPrioritiesSoftware();
    void _testSetCodecPrioritiesHardware();
    void _testRedirectGLibLogging();
    void _testConfigureDebugLoggingIsIdempotent();
    void _testVerifyRequiredPlugins();
    void _testEnvironmentSetup();
    void _testWritePipelineDotReturnsEmptyOnWriteFailure();
    void _testCompleteInit();
    void _testCreateVideoReceiver();
    void _testBindDebugLevelFactRejectsNullContext();
    void _testRuntimeVersionCheck();
    void _testAppsinkFrameDelivery();
    void _testAppsinkYuvPassthrough();
    void _testAppsinkPtsAndColorimetry();
    void _testQgcVideoSinkBinGpuZeroCopyProperty();
    void _testQgcVideoSinkBinRejectsFailedAdopt();
    void _testGlMemoryDispatch();
    void _testD3D11MemoryDispatch();
    void _testD3D12MemoryDispatch();
    void _testD3D11MapTexturesWithQRhi();
    void _testD3D11MapNv12TexturesWithQRhi();
    void _testD3D12MapTexturesWithQRhi();
    void _testD3D12MapNv12TexturesWithQRhi();
    void _testDmaBufDispatch();
    void _testDmaDrmCapsRejectNonLinearModifiers();
    void _testDmaBufRejectsNonLinearDirectImport();
    void _testDmaBufTiledImportAvoidsTexStorage();
    void _testVulkanDispatchDemotesToCpu();
    void _testCapsCacheInvalidation();
    void _testGpuZeroCopyFallback();
    void _testAppsinkTeardownUnderLoad();
    void _testBridgeDispatcherFanout();
    void _testHwBufferMapTexturesGuard();
    void _testFrameCountsTelemetrySignal();
    void _testInactiveQgcQVideoSinkDropsAndCounts();
    void _testGetAppsinkAccessor();
    void _testQVideoSinkControllerClearsElementOnDestroy();
    void _testQVideoSinkControllerClearsElementWhenVideoSinkDestroyed();
    void _testQVideoSinkControllerNullSinkStillDeactivatesOnDestroy();
    void _testQVideoSinkControllerRepeatedSetupKeepsNewBindingActive();
    void _testQVideoSinkControllerNoWindowStartsInactive();
    void _testContextBridgeRegistry();
    void _testHwBufferLifecycleResetsNativeCaches();
    void _testHwFrameTexturesRejectsForeignOldTextures();
    void _testHwBufferFactoryDispatchSystemMemory();
    void _testHwBufferFactoryCacheRejectsMemoryTypeChange();
    void _testDmaBufSingleFdImportEnvGate();
    void _testCpuZeroCopyFrameRejectsWritableMap();
    void _testCpuMemcpyActiveRowStrideHandling();
    void _testQGCRhiCaptureCacheLifecycle();
    void _testColorimetryPixelFormatMapping();
    void _testCpuCapsFormatsRoundTripToQt();
    void _testAllocationQueryHwMemoryPoolHint();
    void _testQgcVideoSinkBinAllocationQueryAdvertisesVideoMeta();
    void _testAllocationQuerySystemMemoryNoPoolStillAdvertisesMetas();
    void _testColorimetryColorSpaceMapping();
    void _testColorimetryResolutionHeuristicMatchesQt();
    void _testColorimetryTransferMapping();
    void _testColorimetryFrameRatePropagation();
    void _testHwBufferCropMatrixIdentityWithoutMeta();
    void _testHwBufferCropMatrixFromVideoCropMeta();
    void _testApplyOrientationToFrameMapping();
    void _testAdapterFlushDropsInFlightSamples();
    void _testSourceFactoryUdpRtpJitterBuffer();
    void _testSourceFactoryJitterBufferNone();
    void _testSourceFactoryNoRetransmission();
    void _testSourceFactoryRtspExcludesStaticJitterBuffer();
    void _testSourceFactoryRejectsBadUri();
    void _testSourceFactoryTcpMpegTs();
    void _testSourceFactoryRejectsBadTcpUri();
    void _testSourceFactoryUdp265Caps();
    void _testSourceFactoryUdp265UsesExplicitDepayAndParser();
    void _testSourceFactoryUdpH264Caps();
    void _testSourceFactoryUdpMpegTs();
    void _testSourceFactorySchemeCaseInsensitive();
    void _testSourceFactoryNegativeLatencyClamped();
    void _testSourceFactoryDynamicRtpLinkFailureCleansJitterBuffer();
    void _testColorimetryColorRangeMapping();
    void _testPixelFormatAcceptedButNotAdvertised();
    void _testAdvertisedFormatListMatchesTable();
    void _testTelemetryMapDurationEwma();
    void _testTelemetryFallbackReasonMatrix();
    void _testTelemetrySyncWaitSplit();
    void _testTelemetryPathStatsFailuresAreNotDelivered();
    void _testTelemetryDmaBufExtraStatsDrain();
};
