function(qgc_test_assert_streq label expected actual)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "ASSERT [${label}]: expected='${expected}' actual='${actual}'")
    endif()
endfunction()

function(qgc_test_assert_in_list label expected_item list_var)
    if(NOT "${expected_item}" IN_LIST ${list_var})
        message(FATAL_ERROR "ASSERT [${label}]: '${expected_item}' not in ${list_var}=${${list_var}}")
    endif()
endfunction()

function(qgc_test_assert_not_in_list label unexpected_item list_var)
    if("${unexpected_item}" IN_LIST ${list_var})
        message(FATAL_ERROR "ASSERT [${label}]: '${unexpected_item}' should not be in ${list_var}=${${list_var}}")
    endif()
endfunction()

function(qgc_test_assert_target label tgt)
    if(NOT TARGET ${tgt})
        message(FATAL_ERROR "ASSERT [${label}]: target '${tgt}' was not created")
    endif()
endfunction()

function(qgc_test_assert_property label tgt prop expected)
    get_target_property(_actual ${tgt} ${prop})
    if(NOT "${_actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "ASSERT [${label}]: ${tgt}.${prop} expected='${expected}' actual='${_actual}'")
    endif()
endfunction()

function(qgc_test_pass label)
    message(STATUS "PASS: ${label}")
endfunction()
