cmake_minimum_required(VERSION 3.22)
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/..")
include("${CMAKE_CURRENT_LIST_DIR}/_assert.cmake")
include(Components)

gstreamer_resolve_component(Base _n _a _p _m)
qgc_test_assert_streq("Base.name" "Base"               "${_n}")
qgc_test_assert_streq("Base.api"  "api_base"           "${_a}")
qgc_test_assert_streq("Base.pc"   "gstreamer-base-1.0" "${_p}")
qgc_test_assert_streq("Base.mandatory" "1"             "${_m}")
qgc_test_pass("resolve_component by ComponentName")

gstreamer_resolve_component(api_video _n _a _p _m)
qgc_test_assert_streq("api_video.name" "Video"               "${_n}")
qgc_test_assert_streq("api_video.api"  "api_video"           "${_a}")
qgc_test_assert_streq("api_video.pc"   "gstreamer-video-1.0" "${_p}")
qgc_test_pass("resolve_component by api_name")

gstreamer_resolve_component(App _n _a _p _m)
qgc_test_assert_streq("App.mandatory" "0" "${_m}")
qgc_test_pass("resolve_component mandatory flag")

gstreamer_resolve_component(Core _n _a _p _m)
qgc_test_assert_streq("Core.name"      "Core" "${_n}")
qgc_test_assert_streq("Core.api"       ""     "${_a}")
qgc_test_assert_streq("Core.pc"        ""     "${_p}")
qgc_test_assert_streq("Core.mandatory" "1"    "${_m}")
qgc_test_pass("resolve_component Core")

gstreamer_resolve_component(api_foo_bar _n _a _p _m)
qgc_test_assert_streq("unknown api name"  ""                       "${_n}")
qgc_test_assert_streq("unknown api"       "api_foo_bar"            "${_a}")
qgc_test_assert_streq("unknown api pc"    "gstreamer-foo-bar-1.0"  "${_p}")
qgc_test_pass("resolve_component fallback")

gstreamer_resolve_component("" _n _a _p _m)
qgc_test_assert_streq("empty query name" "" "${_n}")
qgc_test_assert_streq("empty query api"  "" "${_a}")
qgc_test_assert_streq("empty query pc"   "" "${_p}")
qgc_test_pass("resolve_component empty query")

gstreamer_mandatory_components(_mn _ma)
qgc_test_assert_in_list("mandatory: Core"          Core             _mn)
qgc_test_assert_in_list("mandatory: Base"          Base             _mn)
qgc_test_assert_in_list("mandatory: Gl"            Gl               _mn)
qgc_test_assert_in_list("mandatory: GlPrototypes"  GlPrototypes     _mn)
qgc_test_assert_in_list("mandatory: Rtsp"          Rtsp             _mn)
qgc_test_assert_in_list("mandatory: Video"         Video            _mn)
qgc_test_assert_not_in_list("optional: App"        App              _mn)
qgc_test_assert_in_list("mandatory api: api_base"  api_base         _ma)
qgc_test_assert_not_in_list("Core has no api"      Core             _ma)
qgc_test_pass("mandatory_components")

gstreamer_component_to_api("GlPrototypes" _c2a_glp)
qgc_test_assert_streq("GlPrototypes -> api_gl_prototypes" "api_gl_prototypes" "${_c2a_glp}")
gstreamer_component_to_api("HwBuffers" _c2a_hw)
qgc_test_assert_streq("HwBuffers -> api_hw_buffers" "api_hw_buffers" "${_c2a_hw}")
gstreamer_component_to_api("App" _c2a_app)
qgc_test_assert_streq("App -> api_app" "api_app" "${_c2a_app}")
qgc_test_pass("component_to_api CamelCase")

set(WIN32 OFF)
set(ANDROID OFF)
set(IOS OFF)

gstreamer_build_apis_and_deps(_apis _deps Core)
qgc_test_assert_in_list("seed: api_base"           api_base           _apis)
qgc_test_assert_in_list("seed: api_gl"             api_gl             _apis)
qgc_test_assert_in_list("seed: api_gl_prototypes"  api_gl_prototypes  _apis)
qgc_test_assert_in_list("seed: api_rtsp"           api_rtsp           _apis)
qgc_test_assert_in_list("seed: api_video"          api_video          _apis)
qgc_test_assert_in_list("seed deps: gstreamer-base-1.0" gstreamer-base-1.0 _deps)
qgc_test_pass("build_apis_and_deps Core seed")

gstreamer_build_apis_and_deps(_apis2 _deps2 Core App)
qgc_test_assert_in_list("App -> api_app" api_app _apis2)
qgc_test_assert_in_list("App -> gstreamer-app-1.0" gstreamer-app-1.0 _deps2)
qgc_test_pass("build_apis_and_deps App")

gstreamer_build_apis_and_deps(_apis3 _deps3 Core GlPrototypes)
qgc_test_assert_in_list("GlPrototypes -> api_gl_prototypes" api_gl_prototypes _apis3)
qgc_test_pass("CamelCase -> snake_case")

gstreamer_build_apis_and_deps(_apis4 _deps4 Core Allocators)
qgc_test_assert_in_list("Allocators -> api_allocators" api_allocators _apis4)
qgc_test_assert_in_list("Allocators -> gstreamer-allocators-1.0" gstreamer-allocators-1.0 _deps4)
qgc_test_pass("Allocators mapping")

set(WIN32 ON)
gstreamer_build_apis_and_deps(_apis_win _deps_win Core)
qgc_test_assert_in_list("WIN32 -> graphene-1.0" graphene-1.0 _deps_win)
set(WIN32 OFF)
qgc_test_pass("WIN32 platform extras")

set(ANDROID ON)
gstreamer_build_apis_and_deps(_apis_a _deps_a Core)
qgc_test_assert_in_list("ANDROID -> gio-2.0" gio-2.0 _deps_a)
qgc_test_assert_in_list("ANDROID -> gmodule-2.0" gmodule-2.0 _deps_a)
qgc_test_assert_in_list("ANDROID -> zlib" zlib _deps_a)
set(ANDROID OFF)
qgc_test_pass("ANDROID platform extras")

gstreamer_build_apis_and_deps(_apis_idem _deps_idem Core App App)
list(LENGTH _apis_idem _apis_idem_len)
qgc_test_assert_streq("idempotent apis length" "6" "${_apis_idem_len}")
qgc_test_pass("idempotence")

set(WIN32 OFF)
set(APPLE OFF)
gstreamer_platform_plugin_attrs(_ext _prefix _glob)
qgc_test_assert_streq("linux ext"    "so"             "${_ext}")
qgc_test_assert_streq("linux prefix" "libgst"         "${_prefix}")
qgc_test_assert_streq("linux glob"   "libgst*.so"     "${_glob}")
qgc_test_pass("platform_plugin_attrs linux")

set(WIN32 ON)
gstreamer_platform_plugin_attrs(_ext _prefix _glob)
qgc_test_assert_streq("win ext"    "dll"        "${_ext}")
qgc_test_assert_streq("win prefix" "gst"        "${_prefix}")
qgc_test_assert_streq("win glob"   "gst*.dll"   "${_glob}")
set(WIN32 OFF)
qgc_test_pass("platform_plugin_attrs windows")

set(APPLE ON)
gstreamer_platform_plugin_attrs(_ext _prefix _glob)
qgc_test_assert_streq("apple ext"    "dylib"          "${_ext}")
qgc_test_assert_streq("apple prefix" "libgst"         "${_prefix}")
qgc_test_assert_streq("apple glob"   "libgst*.dylib"  "${_glob}")
set(APPLE OFF)
qgc_test_pass("platform_plugin_attrs apple")
