name: Install Dependencies
description: Install platform-specific build dependencies (GStreamer, etc.)

inputs:
  gstreamer:
    description: 'Install GStreamer (Windows x64 only)'
    required: false
    default: 'true'
  gstreamer-version:
    description: 'GStreamer version (default: from build-config.json)'
    required: false
    default: ''
  vulkan:
    description: 'Install Vulkan SDK (Windows only, for validation layers)'
    required: false
    default: 'false'
  extra-packages:
    description: 'Additional packages to install (space-separated, Linux only)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      uses: nick-fields/retry@v3
      env:
        INPUT_GSTREAMER: ${{ inputs.gstreamer }}
        INPUT_GSTREAMER_VERSION: ${{ inputs.gstreamer-version }}
        INPUT_VULKAN: ${{ inputs.vulkan }}
      with:
        timeout_minutes: 10
        max_attempts: 3
        shell: python
        command: |
          import os, subprocess, sys
          args = [sys.executable, './tools/setup/install_dependencies.py', '--platform', 'windows']
          if os.environ.get('INPUT_GSTREAMER_VERSION'):
              args += ['--gstreamer-version', os.environ['INPUT_GSTREAMER_VERSION']]
          if os.environ.get('INPUT_GSTREAMER') != 'true':
              args.append('--skip-gstreamer')
          if os.environ.get('INPUT_VULKAN') == 'true':
              args.append('--vulkan')
          sys.exit(subprocess.run(args).returncode)

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          python3 tools/setup/install_dependencies.py --platform debian

    - name: Install extra packages (Linux)
      if: runner.os == 'Linux' && inputs.extra-packages != ''
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 3
        command: |
          EXTRA_PACKAGES='${{ inputs.extra-packages }}'
          for pkg in $EXTRA_PACKAGES; do
            if [[ ! "$pkg" =~ ^[a-zA-Z0-9][a-zA-Z0-9.+-]*$ ]]; then
              echo "Error: Invalid package name '$pkg'" >&2
              exit 1
            fi
          done
          # shellcheck disable=SC2086
          sudo apt-get install -y $EXTRA_PACKAGES

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          python3 tools/setup/install_dependencies.py --platform macos
