name: Publish Android Build to Play Store
description: Uploads Android APK to Google Play Store
inputs:
  artifact:
    description: Build File To Upload
    required: true
  service_account_json:
    description: The service account json private key file to authorize the upload request
    required: true
runs:
  using: "composite"
  steps:
    - name: Validate artifact
      shell: bash
      run: |
        if [[ ! -f "${{ inputs.artifact }}" ]]; then
          echo "::error::Artifact not found: ${{ inputs.artifact }}"
          exit 1
        fi

    - name: Deploy to Play Store
      if: github.event_name != 'pull_request' && (github.ref_name == 'master' || github.ref_type == 'tag')
      uses: r0adkll/upload-google-play@v1.1.3
      with:
        serviceAccountJsonPlainText: ${{ inputs.service_account_json }}
        packageName: com.mavlink.qgroundcontrol
        releaseFiles: ${{ inputs.artifact }}
        track: production
        status: completed
