// This file was generated by qtwaylandscanner
// source file is pointer-warp-v1.xml

#ifndef QT_WAYLAND_POINTER_WARP_V1
#define QT_WAYLAND_POINTER_WARP_V1

#include <QtWaylandClient/private/wayland-pointer-warp-v1-client-protocol.h>
#include <QByteArray>
#include <QString>

struct wl_registry;

QT_BEGIN_NAMESPACE
QT_WARNING_PUSH
QT_WARNING_DISABLE_GCC("-Wmissing-field-initializers")
QT_WARNING_DISABLE_CLANG("-Wmissing-field-initializers")
#if !defined(Q_WAYLAND_CLIENT_POINTER_WARP_V1_EXPORT)
#  if defined(QT_SHARED) && !defined(QT_STATIC)
#    if defined(QT_BUILD_WAYLANDCLIENT_LIB)
#      define Q_WAYLAND_CLIENT_POINTER_WARP_V1_EXPORT Q_DECL_EXPORT
#    else
#      define Q_WAYLAND_CLIENT_POINTER_WARP_V1_EXPORT Q_DECL_IMPORT
#    endif
#  else
#    define Q_WAYLAND_CLIENT_POINTER_WARP_V1_EXPORT
#  endif
#endif

namespace QtWayland {
    class Q_WAYLAND_CLIENT_POINTER_WARP_V1_EXPORT wp_pointer_warp_v1
    {
    public:
        wp_pointer_warp_v1(struct ::wl_registry *registry, uint32_t id, int version);
        wp_pointer_warp_v1(struct ::wp_pointer_warp_v1 *object);
        wp_pointer_warp_v1();

        virtual ~wp_pointer_warp_v1();

        void init(struct ::wl_registry *registry, uint32_t id, int version);
        void init(struct ::wp_pointer_warp_v1 *object);

        struct ::wp_pointer_warp_v1 *object() { return m_wp_pointer_warp_v1; }
        const struct ::wp_pointer_warp_v1 *object() const { return m_wp_pointer_warp_v1; }
        static wp_pointer_warp_v1 *fromObject(struct ::wp_pointer_warp_v1 *object);

        bool isInitialized() const;

        uint32_t version() const;
        static const struct ::wl_interface *interface();

        void destroy();
        void warp_pointer(struct ::wl_surface *surface, struct ::wl_pointer *pointer, wl_fixed_t x, wl_fixed_t y, uint32_t serial);

    private:
        struct ::wp_pointer_warp_v1 *m_wp_pointer_warp_v1;
    };
}

QT_WARNING_POP
QT_END_NAMESPACE

#endif
