# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.1.0")
   message(FATAL_ERROR "CMake >= 3.1.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.1.0...3.28)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::Gui)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Qt6::Gui
add_library(Qt6::Gui SHARED IMPORTED)

set_target_properties(Qt6::Gui PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "QT_GUI_LIB"
  INTERFACE_COMPILE_OPTIONS "\$<\$<NOT:\$<COMPILE_LANGUAGE:Swift>>:-fPIC>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/QtGui;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Qt6::Core;WrapOpenGL::WrapOpenGL;\$<TARGET_NAME_IF_EXISTS:WrapVulkanHeaders::WrapVulkanHeaders>"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:${_IMPORT_PREFIX}/./metatypes/qt6gui_metatypes.json>"
  MODULE_PLUGIN_TYPES "accessiblebridge;platforms;platforms_darwin;xcbglintegrations;platformthemes;platforminputcontexts;generic;iconengines;imageformats;egldeviceintegrations;wayland_graphics_integration_client;wayland_decoration_client;wayland_shell_integration"
  QT_DISABLED_PRIVATE_FEATURES "directfb;directwrite;directwrite3;directwritecolrv1;direct2d;direct2d1_1;vxworksevdev;system_harfbuzz;qqnx_imf;integrityfb;libinput;integrityhid;libinput_axis_api;libinput_hires_wheel_support;vsp2;mtdev;eglfs_brcm;eglfs_vsp2;eglfs_mali;eglfs_viv;eglfs_rcar;eglfs_viv_wl;eglfs_openwfd;system_jpeg;system_png;tslib;xcb_native_painting;xrender;xcb_sm;system_xcb_xinput;graphicsframecapture;wayland_brcm;wayland_libhybris_egl_server_buffer"
  QT_DISABLED_PUBLIC_FEATURES "opengles2;opengles3;opengles31;opengles32;dynamicgl;metal;openvg;system_textmarkdownreader"
  QT_ENABLED_PRIVATE_FEATURES "accessibility_atspi_bridge;emojisegmenter;evdev;freetype;system_freetype;fontconfig;harfbuzz;kms;drm_atomic;linuxfb;vnc;vkgen;vkkhrdisplay;egl_x11;eglfs;eglfs_egldevice;eglfs_gbm;eglfs_x11;gif;ico;jpeg;png;imageio_text_loading;tuiotouch;xcb_glx;xcb_egl_plugin;xcb_xlib;xkbcommon;xkbcommon_x11;xlib;multiprocess;raster_64bit;raster_fp;qtgui_threadpool;wayland_client;wayland_server;wayland_egl;wayland_drm_egl_server_buffer;wayland_dmabuf_server_buffer;wayland_shm_emulation_server_buffer;wayland_vulkan_server_buffer;wayland_datadevice;wayland_client_primary_selection;wayland_client_fullscreen_shell_v1;wayland_client_wl_shell;wayland_client_xdg_shell;egl_extension_platform_wayland;run_opengl_tests"
  QT_ENABLED_PUBLIC_FEATURES "accessibility_atspi_bridge;emojisegmenter;freetype;fontconfig;harfbuzz;opengl;vulkan;egl;ico;sessionmanager;xcb;xcb_glx_plugin;texthtmlparser;textmarkdownreader;textmarkdownwriter;textodfwriter;cssparser;draganddrop;action;cursor;clipboard;wheelevent;tabletevent;im;highdpiscaling;validator;standarditemmodel;filesystemmodel;imageformatplugin;movie;imageformat_bmp;imageformat_ppm;imageformat_xbm;imageformat_xpm;imageformat_png;imageformat_jpeg;image_heuristic_mask;image_text;picture;colornames;pdf;desktopservices;systemtrayicon;accessibility;whatsthis;undocommand;undostack;undogroup;wayland;waylandscanner;gbm;kms"
  QT_QMAKE_PRIVATE_CONFIG ""
  QT_QMAKE_PUBLIC_CONFIG ""
  QT_QMAKE_PUBLIC_QT_CONFIG "gbm;kms"
  TRANSITIVE_COMPILE_PROPERTIES "QT_PLUGIN_TARGETS"
  _qt_config_module_name "gui"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_is_public_module "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_has_public_headers "TRUE"
  _qt_module_has_qpa_headers "TRUE"
  _qt_module_has_rhi_headers "TRUE"
  _qt_module_include_name "QtGui"
  _qt_module_interface_name "Gui"
  _qt_module_relative_include_dir "../../../include/QtGui"
  _qt_package_name "Qt6Gui"
  _qt_package_version "6.10.3"
  _qt_private_module_target_name "GuiPrivate"
  _qt_sbom_cydx_bom_serial_number_uuid "d9fbbba0-fb2f-5164-8d02-4bdc7870efc5"
  _qt_sbom_cydx_external_bom_link "urn:cdx:d9fbbba0-fb2f-5164-8d02-4bdc7870efc5/1#SPDXRef-Package-qtbase-qt-module-Gui-18caa008d90e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.10.3.cdx.json"
  _qt_sbom_entity_type "QT_MODULE"
  _qt_sbom_package_name "Gui"
  _qt_sbom_package_version "6.10.3"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-module-Gui-18caa008d90e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.10.3.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-7ddbc87d+HEAD-host-linux-x86_64-target-linux-x86_64-53c2b623-7000-5f77-ad0f-f10743359b4f"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.10.3.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.10.3.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-18caa008d90e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-18caa008d90e:SPDXRef-Package-qtbase-qt-module-Gui-18caa008d90e"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/Qt6GuiTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "Qt6::Core" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
