codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 1  # Only Linux Debug generates coverage
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "30...90"

  status:
    project:
      default:
        target: 30%
        threshold: 2%
        base: auto
        if_ci_failed: success
    patch:
      default:
        target: 30%
        threshold: 5%
        base: auto
        if_ci_failed: success

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false

ignore:
  - "test/**/*"
  - "tools/**/*"
  - "deploy/**/*"
  - "custom/**/*"
  - "libs/**/*"
  - "*.qml"
  - "*.js"
  - "android/**/*"

flags:
  debug:
    paths:
      - src/
    carryforward: true
