changelog:
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: Features
      labels:
        - "RN: MAJOR FEATURE"
        - "RN: MINOR FEATURE"
        - "RN: MAJOR FEATURE - CUSTOM BUILD"
        - "RN: MINOR FEATURE - CUSTOM BUILD"
    - title: Improvements
      labels:
        - "RN: IMPROVEMENT"
        - "RN: IMPROVEMENT - CUSTOM BUILD"
        - "RN: REFACTORING"
    - title: Fixes
      labels:
        - "RN: BUGFIX"
        - "RN: BUGFIX - CUSTOM BUILD"
    - title: Hardware Support
      labels:
        - "RN: NEW BOARD SUPPORT"
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
