extends: default

rules:
  document-start: disable
  line-length:
    max: 200
  comments-indentation: disable
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
