files:
  - source: /docs/en/**/*.md
    translation: /docs/%two_letters_code%/**/%original_file_name%
  - source: /translations/qgc.ts
    translation: /translations/qgc_%locale_with_underscore%.ts
  - source: /translations/qgc-json.ts
    translation: 'translation": "/translations/qgc_%locale_with_underscore%.ts'
