FROM ubuntu:22.04

ARG QT_VERSION=6.6.3

ENV DEBIAN_FRONTEND noninteractive

ENV DISPLAY :99

ENV QT_PATH /opt/Qt
ENV QT_ROOT_DIR $QT_PATH/${QT_VERSION}/android_arm64_v8a
ENV QT_HOST_PATH $QT_PATH/${QT_VERSION}/gcc_64

ENV PATH /usr/lib/ccache:$QT_ROOT_DIR/bin:$PATH

COPY tools/setup/install-dependencies-android-debian.sh /tmp/qt/
RUN /tmp/qt/install-dependencies-android-debian.sh

COPY tools/setup/install-qt-android-debian.sh /tmp/qt/
RUN /tmp/qt/install-qt-android-debian.sh

RUN locale-gen en_US.UTF-8 && dpkg-reconfigure locales

RUN git config --global --add safe.directory /project/source

WORKDIR /project/build
CMD $QT_ROOT_DIR/bin/qt-cmake -S /project/source -B . -G Ninja -DCMAKE_BUILD_TYPE=Release -DQT_HOST_PATH=$QT_HOST_PATH -DQT_ANDROID_BUILD_ALL_ABIS=OFF -DQT_ANDROID_ABIS="arm64-v8a" -DQT_ANDROID_SIGN_APK=OFF ; \
	cmake --build . --target all --config Debug ; \
	cmake --install . --config Debug
