if(COMMAND add_qgc_test)
    target_sources(${CMAKE_PROJECT_NAME} PRIVATE RTCMFramerTest.cc RTCMFramerTest.h)
    target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
    add_qgc_test(RTCMFramerTest LABELS Unit)
else()
    qt_add_executable(QGCRTCMFramerTest RTCMFramerTest.cc RTCMFramerTest.h)
    set_target_properties(QGCRTCMFramerTest PROPERTIES AUTOMOC ON)
    target_compile_definitions(QGCRTCMFramerTest PRIVATE QGC_GPS_STANDALONE_TEST)
    target_link_libraries(QGCRTCMFramerTest PRIVATE QGC::GPSRTCM Qt6::Test)
    add_test(NAME RTCMFramerTest COMMAND QGCRTCMFramerTest)
    set_tests_properties(RTCMFramerTest PROPERTIES LABELS "Unit;GPS" TIMEOUT 60)
endif()

qt_add_executable(QGCRTCMConformanceTest RTCMConformanceTest.cc)
set_target_properties(QGCRTCMConformanceTest PROPERTIES AUTOMOC ON)
target_link_libraries(QGCRTCMConformanceTest PRIVATE QGC::GPSRTCM Qt6::Test)
add_test(NAME RTCMConformanceTest COMMAND QGCRTCMConformanceTest)
set_tests_properties(RTCMConformanceTest PROPERTIES LABELS "Unit;GPS" TIMEOUT 60)
