name: Coverage Comment
description: Post code coverage report as PR comment

inputs:
  pr-number:
    description: Pull request number to comment on
    required: true
  coverage-xml:
    description: Path to coverage XML file (Cobertura format)
    required: true
  baseline-xml:
    description: Path to baseline coverage XML file (optional)
    required: false
    default: ''
  comment-tag:
    description: Tag for updating existing comment
    required: false
    default: coverage-report

runs:
  using: composite
  steps:
    - name: Generate coverage comment
      id: generate
      shell: bash
      env:
        COVERAGE_XML: ${{ inputs.coverage-xml }}
        BASELINE_XML: ${{ inputs.baseline-xml }}
      run: python3 "$GITHUB_ACTION_PATH/../../scripts/coverage-comment.py"

    - name: Post PR comment
      uses: thollander/actions-comment-pull-request@v3
      with:
        pr-number: ${{ inputs.pr-number }}
        comment-tag: ${{ inputs.comment-tag }}
        file-path: coverage-comment.md
