name: Build Action
description: Build a GitHub Action from source when dist hasn't been updated

inputs:
  repo:
    description: 'Repository in owner/repo format (e.g., actions/checkout)'
    required: true
  ref:
    description: 'Branch, tag, or commit SHA to build'
    required: false
    default: 'HEAD'
  output-dir:
    description: 'Output directory for built action'
    required: false
    default: 'build-action'

outputs:
  action-path:
    description: 'Path to the built action directory'
    value: ${{ steps.build.outputs.action_path }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '22'

    - name: Build action from source
      id: build
      shell: bash
      run: |
        python3 "${{ github.workspace }}/.github/scripts/build_action.py" \
          "${{ inputs.repo }}" \
          --ref "${{ inputs.ref }}" \
          --output "${{ github.workspace }}/${{ inputs.output-dir }}"
