name: Build action
description: Build action whose dist hasn't been updated from source
inputs:
  repo:
    description: Target repo to build
    required: true
  ref:
    description: The branch, tag or SHA to checkout
    required: false
    default: master
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}
        path: build-action

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: build-action/package-lock.json

    - name: Build ${{ inputs.repo }}
      run: |
        cd build-action
        npm ci || npm install
        npm run build
      shell: bash
