name: Qt Benchmark Runner
description: Run Qt Test benchmarks and parse output to JSON

inputs:
  binary-path:
    description: 'Path to the QGC binary'
    required: true
  test-filter:
    description: 'Test filter (e.g., MAVLinkBenchmark)'
    default: 'MAVLinkBenchmark'
  output-file:
    description: 'Path for benchmark JSON output'
    default: 'benchmark.json'
  qt-platform:
    description: 'Qt platform plugin (offscreen for headless)'
    default: 'offscreen'

runs:
  using: composite
  steps:
    - name: Run and parse benchmarks
      shell: bash
      run: |
        if command -v python3 >/dev/null 2>&1; then
          py_cmd="python3"
        else
          py_cmd="python"
        fi

        "${py_cmd}" "${{ github.workspace }}/.github/scripts/benchmark_runner.py" \
          --binary "${{ inputs.binary-path }}" \
          --filter "${{ inputs.test-filter }}" \
          --output "${{ inputs.output-file }}" \
          --platform "${{ inputs.qt-platform }}"
