name: Qt Benchmark Runner
description: Run Qt Test benchmarks and parse output to JSON

inputs:
  binary-path:
    description: 'Path to the QGC binary'
    required: true
  test-filter:
    description: 'Test filter (e.g., MAVLinkBenchmark)'
    default: 'MAVLinkBenchmark'
  output-file:
    description: 'Path for benchmark JSON output'
    default: 'benchmark.json'
  qt-platform:
    description: 'Qt platform plugin (offscreen for headless)'
    default: 'offscreen'

outputs:
  has_results:
    description: 'Whether benchmark results were found'
    value: ${{ steps.parse.outputs.has_results }}
  result_count:
    description: 'Number of benchmark results parsed'
    value: ${{ steps.parse.outputs.result_count }}
  benchmark_file:
    description: 'Path to the benchmark JSON file'
    value: ${{ inputs.output-file }}

runs:
  using: composite
  steps:
    - name: Run and parse benchmarks
      id: parse
      shell: bash
      run: |
        python3 "${{ github.workspace }}/.github/scripts/benchmark_runner.py" \
          --binary "${{ inputs.binary-path }}" \
          --filter "${{ inputs.test-filter }}" \
          --output "${{ inputs.output-file }}" \
          --platform "${{ inputs.qt-platform }}"
