"""Tests for the gps_protocol_defs generator (typed UBX/SBF definitions from pyubx2/pysbf2)."""

from __future__ import annotations

import copy
import importlib.util
import re
import shutil
from typing import TYPE_CHECKING, Any

import pytest
from generators.gps_protocol_defs.definitions import (
    DefinitionError,
    cfg_value_bytes,
    resolve,
    upper_snake,
)
from generators.gps_protocol_defs.generate import OUTPUTS, REPO_ROOT, generate, main, render
from generators.gps_protocol_defs.manifest import load_manifest, parse_manifest
from generators.gps_protocol_defs.upstream import SBFDatabase, UBXDatabase

if TYPE_CHECKING:
    from collections.abc import Callable

UPSTREAM_INSTALLED = all(importlib.util.find_spec(name) for name in ("pyubx2", "pysbf2"))


def _ubx() -> UBXDatabase:
    return UBXDatabase(
        version="9.9",
        classes={0x01: "NAV", 0x06: "CFG"},
        messages={(0x01, 0x07): "NAV-PVT", (0x06, 0x8A): "CFG-VALSET"},
        config_keys={
            "CFG_RATE_MEAS": (0x30210001, "U002"),
            "CFG_TMODE_LAT_HP": (0x2003000C, "I001"),
            "CFG_NAVSPG_DAHEADING_OFFSET": (0x401100E4, "U004"),
            "CFG_MSGOUT_UBX_NAV_PVT_I2C": (0x20910006, "U001"),
            "CFG_MSGOUT_UBX_NAV_PVT_UART1": (0x20910007, "U001"),
            "CFG_MSGOUT_UBX_NAV_PVT_USB": (0x20910009, "U001"),
        },
    )


def _sbf() -> SBFDatabase:
    mode = ("X001", {"Type": "U004", "Reserved1": "U002", "AutoSet": "U001", "2D": "U001"})
    return SBFDatabase(
        version="8.8",
        sync=b"$@",
        block_ids={"PVTGeodetic": 4007},
        blocks={
            "PVTGeodetic": {
                "TOW": "U004",
                "WNc": "U002",
                "Mode": mode,
                "Error": "U001",
                "Latitude": "F008",
                "N": "U001",
                "Satellites": ("N", {"SVID": "U001"}),
                "AfterGroup": "U002",
            }
        },
    )


def _manifest_data() -> dict[str, Any]:
    return {
        "ubx": {
            "msgout-ports": ["UART1", "USB"],
            "messages": {"NAV-PVT": [0x01, 0x07], "CFG-VALSET": [0x06, 0x8A]},
            "keys": {
                "CFG_RATE_MEAS": {"id": 0x30210001, "type": "uint16_t"},
                "CFG_TMODE_LAT_HP": {"id": 0x2003000C, "type": "int8_t"},
                "CFG_NAVSPG_DAHEADING_OFFSET": {
                    "id": 0x401100E4,
                    "type": "int32_t",
                    "upstream-type": "U004",
                },
            },
            "msgout": {"CFG_MSGOUT_UBX_NAV_PVT": 0x20910006},
        },
        "sbf": {
            "blocks": {
                "PVTGeodetic": {
                    "id": 4007,
                    "fields": {
                        "TOW": {"member": "tow", "type": "uint32_t", "offset": 8},
                        "Mode": {"member": "mode", "type": "uint8_t", "offset": 14},
                        "Latitude": {"member": "latitude", "type": "double", "offset": 16},
                    },
                    "bits": {
                        "Mode": {
                            "Type": {"accessor": "modeType", "mask": 0x0F},
                            "2D": {"accessor": "mode2D", "mask": 0x80},
                        }
                    },
                }
            }
        },
    }


def _resolve(data: dict[str, Any], ubx: UBXDatabase | None = None, sbf: SBFDatabase | None = None):
    return resolve(parse_manifest(data, "test"), ubx or _ubx(), sbf or _sbf())


def _reversed_tables(data: dict[str, Any]) -> dict[str, Any]:
    data = copy.deepcopy(data)
    for table in ("messages", "keys", "msgout"):
        data["ubx"][table] = dict(reversed(data["ubx"][table].items()))
    return data


@pytest.mark.parametrize(
    ("key_id", "size"),
    [
        (0x10000000, 1),
        (0x20000000, 1),
        (0x30000000, 2),
        (0x40000000, 4),
        (0x50000000, 8),
        (0x00000000, 0),
        (0x60000000, 0),
        (0x70000000, 0),
        (0x8FFFFFFF, 0),
    ],
)
def test_size_bits(key_id: int, size: int) -> None:
    assert cfg_value_bytes(key_id) == size


def test_render_is_deterministic_and_independent_of_manifest_order() -> None:
    first = render(_resolve(_manifest_data()))
    assert first == render(_resolve(_manifest_data()))
    assert first == render(_resolve(_reversed_tables(_manifest_data())))
    assert set(first) == set(OUTPUTS.values())
    for text in first.values():
        assert text.splitlines()[0] == (
            "// Generated by tools/generators/gps_protocol_defs from pyubx2 9.9 / pysbf2 8.8 "
            "(BSD-3-Clause). Do not edit."
        )
        assert text.endswith("\n")
        assert not text.endswith("\n\n")


def test_resolved_definitions() -> None:
    definitions = _resolve(_manifest_data())
    assert [(m.constant, m.class_constant, m.id) for m in definitions.messages] == [
        ("NAV_PVT", "NAV", 0x07),
        ("CFG_VALSET", "CFG", 0x8A),
    ]
    assert [(k.constant, k.type, k.upstream_type) for k in definitions.keys] == [
        ("NAVSPG_DAHEADING_OFFSET", "int32_t", "U4"),
        ("RATE_MEAS", "uint16_t", "U2"),
        ("TMODE_LAT_HP", "int8_t", "I1"),
    ]
    assert [(p.name, p.offset) for p in definitions.ports] == [("UART1", 1), ("USB", 3)]
    assert definitions.msgout[0].port_ids == (("UART1", 0x20910007), ("USB", 0x20910009))
    block = definitions.blocks[0]
    assert (block.constant, block.size) == ("PVT_GEODETIC", 24)
    assert [(b.accessor, b.type, b.mask, b.shift) for b in block.fields[1].bits] == [
        ("modeType", "uint8_t", 0x0F, 0),
        ("mode2D", "bool", 0x80, 7),
    ]
    assert definitions.notes == (
        "UBX key CFG_NAVSPG_DAHEADING_OFFSET: QGC keeps int32_t; pyubx2 9.9 declares U004",
    )


def _set(path: tuple[str, ...], value: object) -> Callable[[dict[str, Any]], None]:
    def mutate(data: dict[str, Any]) -> None:
        node = data
        for key in path[:-1]:
            node = node[key]
        node[path[-1]] = value

    return mutate


def _delete(path: tuple[str, ...]) -> Callable[[dict[str, Any]], None]:
    def mutate(data: dict[str, Any]) -> None:
        node = data
        for key in path[:-1]:
            node = node[key]
        del node[path[-1]]

    return mutate


PVT = ("sbf", "blocks", "PVTGeodetic")


@pytest.mark.parametrize(
    ("mutate", "problem"),
    [
        pytest.param(
            _set(("ubx", "messages", "NAV-FOO"), [0x01, 0x99]),
            "UBX message NAV-FOO: QGC uses [0x01, 0x99], missing from pyubx2 9.9",
            id="message-missing",
        ),
        pytest.param(
            _set(("ubx", "messages", "NAV-PVT"), [0x01, 0x08]),
            "UBX message NAV-PVT: QGC uses [0x01, 0x08], pyubx2 9.9 has [0x01, 0x07]",
            id="message-id",
        ),
        pytest.param(
            _set(("ubx", "keys", "CFG_FOO"), {"id": 0x10000001, "type": "uint8_t"}),
            "UBX key CFG_FOO: missing from pyubx2 9.9",
            id="key-missing",
        ),
        pytest.param(
            _set(("ubx", "keys", "CFG_RATE_MEAS", "id"), 0x30210002),
            "UBX key CFG_RATE_MEAS: QGC uses id 0x30210002, pyubx2 9.9 has 0x30210001",
            id="key-id",
        ),
        pytest.param(
            _set(("ubx", "keys", "CFG_TMODE_LAT_HP", "type"), "uint8_t"),
            "UBX key CFG_TMODE_LAT_HP: QGC writes uint8_t, pyubx2 9.9 type I001 is int8_t",
            id="key-signedness",
        ),
        pytest.param(
            _set(("ubx", "keys", "CFG_RATE_MEAS", "type"), "uint32_t"),
            "UBX key CFG_RATE_MEAS: QGC type uint32_t does not fit key id 0x30210001",
            id="key-type-size",
        ),
        pytest.param(
            _set(("ubx", "keys", "CFG_NAVSPG_DAHEADING_OFFSET", "upstream-type"), "I004"),
            "UBX key CFG_NAVSPG_DAHEADING_OFFSET: reviewed against pyubx2 type I004, pyubx2 9.9 has U004",
            id="key-acknowledged-type-changed",
        ),
        pytest.param(
            _set(("ubx", "keys", "CFG_RATE_MEAS", "upstream-type"), "U002"),
            "UBX key CFG_RATE_MEAS: upstream-type is stale; pyubx2 9.9 type U002 is uint16_t",
            id="key-acknowledgement-stale",
        ),
        pytest.param(
            _set(("ubx", "msgout", "CFG_MSGOUT_UBX_NAV_PVT"), 0x20910005),
            "UBX key CFG_MSGOUT_UBX_NAV_PVT_I2C: QGC uses U1 key 0x20910005, pyubx2 9.9 has U001 key 0x20910006",
            id="msgout-id",
        ),
        pytest.param(
            _set(("ubx", "msgout-ports"), ["UART1", "SPI"]),
            "UBX key CFG_MSGOUT_UBX_NAV_PVT_SPI: missing from pyubx2 9.9",
            id="msgout-port-missing",
        ),
        pytest.param(
            _set(("ubx", "msgout-ports"), ["I2C"]),
            "UBX msgout-ports must be distinct ports other than I2C",
            id="msgout-port-base",
        ),
        pytest.param(
            _set((*PVT, "id"), 4008),
            "SBF block PVTGeodetic: QGC uses id 4008, pysbf2 8.8 has 4007",
            id="block-id",
        ),
        pytest.param(
            _set(("sbf", "blocks", "PVTCartesian"), {"id": 4006, "fields": {}}),
            "SBF block PVTCartesian: missing from pysbf2 8.8",
            id="block-missing",
        ),
        pytest.param(
            _set((*PVT, "fields", "Latitude", "offset"), 18),
            "SBF PVTGeodetic.Latitude: QGC decodes double at offset 18, pysbf2 8.8 has F008 (double) at offset 16",
            id="field-offset",
        ),
        pytest.param(
            _set((*PVT, "fields", "Latitude", "type"), "float"),
            "SBF PVTGeodetic.Latitude: QGC decodes float at offset 16, pysbf2 8.8 has F008 (double) at offset 16",
            id="field-type",
        ),
        pytest.param(
            _set((*PVT, "fields", "Height"), {"member": "height", "type": "double", "offset": 24}),
            "SBF PVTGeodetic.Height: missing from pysbf2 8.8",
            id="field-missing",
        ),
        pytest.param(
            _set(
                (*PVT, "fields", "AfterGroup"),
                {"member": "after", "type": "uint16_t", "offset": 26},
            ),
            "SBF PVTGeodetic.AfterGroup: not at a fixed offset in pysbf2 8.8",
            id="field-after-group",
        ),
        pytest.param(
            _set((*PVT, "bits", "Mode", "AutoSet"), {"accessor": "modeAutoSet", "mask": 0x20}),
            "SBF PVTGeodetic.Mode.AutoSet: QGC masks 0x20, pysbf2 8.8 has 0x40",
            id="bit-mask",
        ),
        pytest.param(
            _set((*PVT, "bits", "Mode", "3D"), {"accessor": "mode3D", "mask": 0x80}),
            "SBF PVTGeodetic.Mode.3D: missing from pysbf2 8.8",
            id="bit-missing",
        ),
        pytest.param(
            _set((*PVT, "fields", "Latitude", "member"), "Latitude"),
            "SBF member 'Latitude' is not a valid C++ identifier for this header",
            id="member-name",
        ),
    ],
)
def test_validation_reports_disagreement(
    mutate: Callable[[dict[str, Any]], None], problem: str
) -> None:
    data = _manifest_data()
    mutate(data)
    with pytest.raises(DefinitionError) as error:
        _resolve(data)
    assert problem in error.value.problems


def test_validation_reports_every_problem() -> None:
    data = _manifest_data()
    _set(("ubx", "messages", "NAV-PVT"), [0x01, 0x08])(data)
    _set((*PVT, "id"), 4008)(data)
    with pytest.raises(DefinitionError) as error:
        _resolve(data)
    assert len(error.value.problems) == 2


def test_upstream_type_must_fit_its_key_id() -> None:
    ubx = _ubx()
    keys = dict(ubx.config_keys, CFG_RATE_MEAS=(0x30210001, "U004"))
    with pytest.raises(DefinitionError) as error:
        _resolve(_manifest_data(), UBXDatabase(ubx.version, ubx.classes, ubx.messages, keys))
    assert error.value.problems == [
        "UBX key CFG_RATE_MEAS: pyubx2 9.9 type U004 does not fit key id 0x30210001"
    ]


def test_irregular_msgout_port_offsets() -> None:
    ubx = _ubx()
    keys = dict(
        ubx.config_keys,
        CFG_MSGOUT_UBX_NAV_SAT_I2C=(0x20910015, "U001"),
        CFG_MSGOUT_UBX_NAV_SAT_UART1=(0x20910017, "U001"),
        CFG_MSGOUT_UBX_NAV_SAT_USB=(0x20910018, "U001"),
    )
    data = _manifest_data()
    data["ubx"]["msgout"]["CFG_MSGOUT_UBX_NAV_SAT"] = 0x20910015
    with pytest.raises(DefinitionError) as error:
        _resolve(data, UBXDatabase(ubx.version, ubx.classes, ubx.messages, keys))
    assert error.value.problems == [
        "UBX MSGOUT port UART1: pyubx2 9.9 key offsets from I2C differ: [1, 2]"
    ]


@pytest.mark.parametrize(
    ("mutate", "message"),
    [
        pytest.param(_set(("ubx", "extra"), {}), "unknown ubx key(s): extra", id="unknown-key"),
        pytest.param(
            _set(("ubx", "messages", "NAV-PVT"), [1]), "must be [class, id]", id="message-shape"
        ),
        pytest.param(
            _set(("ubx", "keys", "CFG_RATE_MEAS", "id"), "0x30210001"),
            "must be a non-negative integer",
            id="key-id-type",
        ),
        pytest.param(
            _set((*PVT, "bits", "Error"), {"Flag": {"accessor": "errorFlag", "mask": 1}}),
            "bits names unlisted field(s): Error",
            id="bits-unlisted-field",
        ),
    ],
)
def test_manifest_shape_errors(mutate: Callable[[dict[str, Any]], None], message: str) -> None:
    data = _manifest_data()
    mutate(data)
    with pytest.raises(ValueError, match=re.escape(message)):
        parse_manifest(data, "test")


@pytest.mark.parametrize(
    ("name", "constant"),
    [("PVTGeodetic", "PVT_GEODETIC"), ("NAV-PVT", "NAV_PVT"), ("RTCM3-1005", "RTCM3_1005")],
)
def test_upper_snake(name: str, constant: str) -> None:
    assert upper_snake(name) == constant


@pytest.mark.skipif(not UPSTREAM_INSTALLED, reason="needs the gps-defs dependency group")
def test_checked_in_manifest_matches_pinned_upstream() -> None:
    from generators.gps_protocol_defs.upstream import load_sbf, load_ubx

    definitions = resolve(load_manifest(), load_ubx(), load_sbf())
    assert (len(definitions.messages), len(definitions.keys), len(definitions.msgout)) == (
        47,
        46,
        26,
    )
    assert [block.name for block in definitions.blocks] == ["PVTGeodetic"]
    assert len(definitions.notes) == 1


@pytest.mark.skipif(
    not UPSTREAM_INSTALLED or shutil.which("clang-format") is None,
    reason="needs the gps-defs dependency group",
)
def test_checked_in_headers_are_current(capsys: pytest.CaptureFixture[str]) -> None:
    assert generate() == generate()
    assert main(["--check"]) == 0, capsys.readouterr().err
    for path in OUTPUTS.values():
        assert (REPO_ROOT / path).is_file()
