name: Bug report
description: Create a report to help us improve
labels: ["Report: Bug"]

body:
  - type: markdown
    attributes:
      value: |
        The following template is for Issue/Bug reporting only. https://docs.qgroundcontrol.com/en/support/support.html#github-issues

        For questions about how to use or build QGC see: http://qgroundcontrol.com/#resources

        If you are using an old stable release please upgrade first and verify your issue before reporting.

  - type: textarea
    id: description
    attributes:
      label: Description  **(required)**
      description: |
        Please describe your issue in detail. Include:
        1. **Expected Behavior** – What you expected to happen.
        2. **Current Behavior** – What actually happened instead.
        3. **Steps To Reproduce** – Step-by-step list of actions to reproduce the issue.
        3. **Additional Details** – Any other context that helps explain the problem.
      placeholder: |
        **Expected Behavior**
        Describe what you thought should happen here.

        **Current Behavior**
        Describe what actually happened here.

        **Steps To Reproduce**
        1.
        2.
        3.

        **Additional Details**
        Add any extra info (errors, warnings, etc.) here.
    validations:
      required: true

  - type: textarea
    id: system-information
    attributes:
      label: System Information
      description: When posting bug reports, include the following information.
      placeholder: |
        - QGC Version: [e.g. 4.4.0] **(required)**
        - QGC build: [e.g. daily, stable, self-built from source, etc...]
        - Operating System: [e.g. Windows 11, Ubuntu 22.04, macOS 15, iOS 17 ]
        - Flight Controller: [e.g. CubePilot Cube Orange, Pixhawk 6X, etc.]
        - Autopilot Software (with version): [e.g., PX4 1.15.4, ArduCopter 4.5.7 ]
      validations:
        required: true

  - type: textarea
    id: logs-screenshots
    attributes:
      label: Log Files and Screenshots
      description: Include links to QGC Console Logs, autopilot logs, and screenshots.
      placeholder: |
        - [QGC Console Logs](https://docs.qgroundcontrol.com/en/settings_view/console_logging.html)
        - Autopilot logs when available (post a link)
        - Screenshots of QGC to help identify the issue.
