name: Feature request
description: Tell us about your new idea
labels: ["enhancement"]
type: feature

body:
  - type: markdown
    attributes:
      value: |
        Tell us a bit about the feature:
        - What problem does it solve?
        - What does it do?
        - Are there other systems that have this feature?
        - What communication/integration standards does the feature rely on (e.g. MAVLink commands etc)

        Any additional context you can provide will make the feature easier to evaluate (e.g. mockups, detailed specification, etc).

  - type: textarea
    id: description
    attributes:
      label: Feature Description
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem does this feature solve? Describe the scenario where this would be useful.
      placeholder: "As a user, I want to... so that I can..."

  - type: dropdown
    id: flight-stacks
    attributes:
      label: Flight Stacks
      description: Select the flight stacks the feature must work with.
      multiple: true
      options:
        - PX4
        - ArduPilot

  - type: dropdown
    id: vehicle-types
    attributes:
      label: Vehicle Types
      description: Select the relevant vehicle types for this feature.
      multiple: true
      options:
        - Multirotor
        - Fixed-wing
        - VTOL
        - Rover
        - Boat
        - Submarine

  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      description: Select the platforms this feature should work on.
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - All
