name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["needs-triage"]
type: feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please describe your idea in detail below.

  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-Submission Checklist
      description: Please verify the following
      options:
        - label: I have searched for existing feature requests and this is not a duplicate
          required: true
        - label: I have reviewed the roadmap and this feature is not already planned
          required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which category best describes this feature?
      options:
        - Flight Display / UI
        - Mission Planning
        - Vehicle Setup / Configuration
        - Video / Camera
        - Telemetry / Logging
        - Communication / Links
        - Maps / Terrain
        - Multi-Vehicle Support
        - Firmware Integration (PX4)
        - Firmware Integration (ArduPilot)
        - Developer Tools / API
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What workflow would it improve?
      placeholder: |
        As a [type of user], I want to [do something], so that [benefit/value].
        Currently, I have to [workaround], which is [painful/inefficient/etc.].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: |
        The feature would work like this:
        1. User opens [menu/panel]
        2. User configures [settings]
        3. System does [action]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...
        - Current workaround: ...
    validations:
      required: false

  - type: dropdown
    id: platforms
    attributes:
      label: Target Platforms
      description: Which platforms should support this feature?
      multiple: true
      options:
        - All Platforms
        - Desktop Only (Windows/macOS/Linux)
        - Mobile Only (Android/iOS)
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
    validations:
      required: true

  - type: dropdown
    id: firmware
    attributes:
      label: Firmware Compatibility
      description: Which firmware should this work with?
      multiple: true
      options:
        - All Firmware
        - PX4 Only
        - ArduPilot Only
        - Firmware Independent
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If you have mockups, screenshots from other apps, or examples, please share them
      placeholder: Drag and drop images here
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Perspective)
      description: How important is this feature to you?
      options:
        - Critical (Blocking my workflow)
        - High (Significant improvement)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Willingness to Contribute
      description: Are you willing to help implement this feature?
      options:
        - Yes, I can implement this feature
        - Yes, I can help with testing
        - Yes, I can help with documentation
        - No, but I can provide requirements/feedback
        - No, just suggesting
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: |
        - Similar features in other GCS software
        - Technical constraints to consider
        - Compatibility concerns
    validations:
      required: false
