name: Question / Help
description: Ask a question or get help with QGroundControl
title: "[Question]: "
labels: []
type: question
body:
  - type: markdown
    attributes:
      value: |
        **Before asking a question**, please check:
        - [User Manual](https://docs.qgroundcontrol.com/)
        - [Developer Guide](https://dev.qgroundcontrol.com/)
        - [Discussion Forum](https://discuss.px4.io/c/qgroundcontrol)
        - [Existing Issues](https://github.com/mavlink/qgroundcontrol/issues)

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation / Setup
        - Vehicle Connection
        - Flight Planning
        - Flight Operations
        - Video Streaming
        - Telemetry / Logging
        - Vehicle Configuration
        - Building from Source
        - Custom Builds
        - Plugin Development
        - General Usage
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please be as specific as possible
      placeholder: What do you want to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context
      placeholder: |
        - QGroundControl version
        - Platform (Windows/macOS/Linux/Android/iOS)
        - Firmware (PX4/ArduPilot)
        - What you've already tried
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your question
      placeholder: Drag and drop images here
    validations:
      required: false
