name: Android Qt
description: Install Qt for Android
inputs:
  host:
    description: Host
    required: true
  arch:
    description: Arch
    required: true
  version:
    description: Qt Version
    required: true
  modules:
    description: Qt Modules
    required: true
  abis:
    description: ABIs to Build
    required: false
    default: 'arm64-v8a;armeabi-v7a'
  cpm-modules:
    description: CPM Cache Path
    required: false
  build-type:
    description: Build Type (Debug or Release)
    required: false
    default: Release
  ndk-full-version:
    description: Android NDK full version (use build-config.outputs.ndk_full_version)
    required: false
    default: '27.2.12479018'
  java-version:
    description: Java version (use build-config.outputs.java_version)
    required: false
    default: '17'
  android-platform:
    description: Android platform/API level (use build-config.outputs.android_platform)
    required: false
    default: '35'
  android-cmdline-tools:
    description: Android cmdline-tools version (use build-config.outputs.android_cmdline_tools)
    required: false
    default: '13114758'
  android-build-tools:
    description: Android build-tools version (use build-config.outputs.android_build_tools)
    required: false
    default: '35.0.0'
  save-cache:
    description: Save cache (set to false for PR builds)
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Setup Java Environment
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ inputs.save-cache != 'true' }}
        gradle-home-cache-cleanup: true

    - name: Setup Android Environment
      uses: android-actions/setup-android@v3
      id: setup-android
      with:
        cmdline-tools-version: ${{ inputs.android-cmdline-tools }}
        packages: 'platform-tools platforms;android-${{ inputs.android-platform }} build-tools;${{ inputs.android-build-tools }} ndk;${{ inputs.ndk-full-version }}'
        log-accepted-android-sdk-licenses: false

    - name: Update Android SDK / NDK / Tools
      shell: bash
      run: |
        ANDROID_SDK_ROOT_UNIX="${ANDROID_SDK_ROOT//\\//}"
        NDK_PATH="${ANDROID_SDK_ROOT_UNIX}/ndk/${{ inputs.ndk-full-version }}"
        if [[ ! -d "$NDK_PATH" ]]; then
          echo "::error::NDK path not found: $NDK_PATH"
          exit 1
        fi
        echo "ANDROID_NDK_ROOT=${NDK_PATH}" >> "$GITHUB_ENV"
        echo "ANDROID_NDK_HOME=${NDK_PATH}" >> "$GITHUB_ENV"
        echo "ANDROID_NDK=${NDK_PATH}" >> "$GITHUB_ENV"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          "${ANDROID_SDK_ROOT}"/cmdline-tools/latest/bin/sdkmanager.bat --update
          "${GITHUB_WORKSPACE}"/android/gradlew.bat --version
        else
          sdkmanager --update
          "${GITHUB_WORKSPACE}"/android/gradlew --version
        fi

    - name: Setup Caching
      uses: ./.github/actions/cache
      with:
        host: ${{ inputs.host }}
        target: android
        build-type: ${{ inputs.build-type }}
        cpm-modules: ${{ inputs.cpm-modules }}
        save-cache: ${{ inputs.save-cache }}

    - name: Install Qt (Host)
      uses: ./.github/actions/qt-install
      with:
        version: ${{ inputs.version }}
        host: ${{ inputs.host }}
        target: desktop
        arch: ${{ inputs.arch }}
        modules: ${{ inputs.modules }}

    - name: Install Qt for Android (arm64_v8a)
      if: contains(inputs.abis, 'arm64-v8a')
      uses: ./.github/actions/qt-install
      with:
        version: ${{ inputs.version }}
        host: ${{ inputs.host }}
        target: android
        arch: android_arm64_v8a
        modules: ${{ inputs.modules }}

    - name: Install Qt for Android (armv7)
      if: contains(inputs.abis, 'armeabi-v7a')
      uses: ./.github/actions/qt-install
      with:
        version: ${{ inputs.version }}
        host: ${{ inputs.host }}
        target: android
        arch: android_armv7
        modules: ${{ inputs.modules }}

    - name: Install Qt for Android (x86_64)
      if: contains(inputs.abis, 'x86_64')
      uses: ./.github/actions/qt-install
      with:
        version: ${{ inputs.version }}
        host: ${{ inputs.host }}
        target: android
        arch: android_x86_64
        modules: ${{ inputs.modules }}

    - name: Install Qt for Android (x86)
      if: contains(inputs.abis, 'x86')
      uses: ./.github/actions/qt-install
      with:
        version: ${{ inputs.version }}
        host: ${{ inputs.host }}
        target: android
        arch: android_x86
        modules: ${{ inputs.modules }}
