name: Common Setup
description: Common Setup for All Runners
runs:
  using: composite
  steps:
    - uses: lukka/get-cmake@latest

    - uses: actions/setup-python@v6
      with:
        python-version: '>=3.9'

    - name: Create build directory
      shell: bash
      run: mkdir -p "$RUNNER_TEMP/build"
