/*******************************************************/
/**  Autogenerated lts rules (regex) for cmu     */
/**  from wfst/    */
/*******************************************************/

#include "cst_string.h"
#include "cst_lts.h"
#include "cst_lexicon.h"

const char * const cmu_lts_phone_table[76] = 
{
    "epsilon",
    "eh1",
    "aa1",
    "ey1",
    "aw1",
    "ax0",
    "ao1",
    "ay0",
    "aa0",
    "ey0",
    "ae1",
    "ih1",
    "aw0",
    "ow0",
    "ao0",
    "ow1",
    "eh0",
    "ih0",
    "w-ey1",
    "w-ax0",
    "y-ax0",
    "ae0",
    "ay1",
    "ah0",
    "ah1",
    "b",
    "ch",
    "k",
    "s",
    "t-s",
    "sh",
    "d",
    "t",
    "jh",
    "iy1",
    "iy0",
    "uw1",
    "y-uw1",
    "oy1",
    "y-uw0",
    "uw0",
    "oy0",
    "f",
    "g",
    "zh",
    "hh",
    "y",
    "l",
    "ax0-l",
    "m",
    "ax0-m",
    "m-ae1",
    "m-ax0",
    "ng",
    "n",
    "n-y",
    "uh1",
    "uh0",
    "w",
    "w-ah1",
    "er1",
    "p",
    "r",
    "er0",
    "z",
    "th",
    "dh",
    "y-er0",
    "y-uh1",
    "y-er1",
    "v",
    "k-s",
    "g-zh",
    "k-sh",
    "g-z",
    NULL
};

const char * const cmu_lts_letter_table[30] = 
{
    "nothing",
    "#",
    "0",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    NULL
};

const cst_lts_addr cmu_lts_letter_index[27] = 
{
    0, /* a */
    5371, /* b */
    5414, /* c */
    6048, /* d */
    6256, /* e */
    10649, /* f */
    10666, /* g */
    11293, /* h */
    11522, /* i */
    15403, /* j */
    15514, /* k */
    15533, /* l */
    15900, /* m */
    15942, /* n */
    16176, /* o */
    19793, /* p */
    19830, /* q */
    19831, /* r */
    21775, /* s */
    22667, /* t */
    22957, /* u */
    24709, /* v */
    24719, /* w */
    24877, /* x */
    24923, /* y */
    25377, /* z */
    0
};

