name: Upload Release
description: Upload release artifact to GitHub and optionally to AWS

inputs:
  artifact_name:
    description: Artifact filename
    required: true
  package_name:
    description: Package name (for GitHub artifact)
    required: true
  aws_key_id:
    description: AWS access key ID
    required: false
  aws_secret_access_key:
    description: AWS secret access key
    required: false
  aws_distribution_id:
    description: AWS CloudFront distribution ID
    required: false
  upload_aws:
    description: Upload artifact to AWS
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Save artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.package_name }}
        path: ${{ runner.temp }}/build/${{ inputs.artifact_name }}

    - name: Attest build provenance
      if: github.event_name == 'push' && github.repository_owner == 'mavlink'
      uses: actions/attest-build-provenance@v3
      with:
        subject-path: ${{ runner.temp }}/build/${{ inputs.artifact_name }}

    - name: Upload to AWS
      if: >-
        fromJSON(inputs.upload_aws) &&
        github.event_name == 'push' &&
        github.repository_owner == 'mavlink' &&
        inputs.aws_key_id != '' &&
        inputs.aws_secret_access_key != ''
      uses: ./.github/actions/aws-upload
      with:
        artifact_name: ${{ inputs.artifact_name }}
        artifact_path: ${{ runner.temp }}/build/${{ inputs.artifact_name }}
        aws_key_id: ${{ inputs.aws_key_id }}
        aws_secret_access_key: ${{ inputs.aws_secret_access_key }}
        aws_distribution_id: ${{ inputs.aws_distribution_id }}
