#!/usr/bin/env python3
"""Regenerate/check offline C++ expectations with the pinned SEMU decoder tools."""

import argparse
import hashlib
import io
import json
from importlib.metadata import distribution
from pathlib import Path

from pynmeagps import NMEAReader
from pyrtcm import RTCMReader
from pysbf2 import SBFReader
from pyubx2 import UBXReader

ROOT = Path(__file__).resolve().parent
PINS = {
    "pyubx2": "9eadeeefc25162206a9200eea1a90bbb8ca315b9",
    "pysbf2": "7ea5e3aecb1349396d47f80938cfe20c461af95b",
    "pynmeagps": "0dd3a69752b6df4172e31255748bf794082845cb",
    "pyrtcm": "620833ee9031207d6181c4818f32b20bab31f9b5",
}


def generate() -> str:
    for package, revision in PINS.items():
        metadata = json.loads(distribution(package).read_text("direct_url.json") or "{}")
        if metadata.get("vcs_info", {}).get("commit_id") != revision:
            raise RuntimeError(f"Install the pinned {package} from fixtures/requirements.txt")
    lines = [
        "// Generated by generate_expectations.py; do not edit.",
        "#pragma once",
        "",
        "// clang-format off",
        "namespace GPSFixture {",
    ]
    for filename in (
        "navigation.ubx",
        "mixed.gps",
        "geodetic.sbf",
        "attitude.sbf",
        "relative.ubx",
        "gga.nmea",
    ):
        digest = hashlib.sha256((ROOT / filename).read_bytes()).hexdigest()
        lines.append(f"// {filename}: sha256 {digest}")
    lines += [
        "struct Position { unsigned offset, size; double latitude, longitude, altitude; };",
        "inline constexpr Position positions[] = {",
    ]
    stream = io.BytesIO((ROOT / "navigation.ubx").read_bytes())
    for raw, msg in UBXReader(stream, quitonerror=2):
        if msg.identity in ("NAV-PVT", "NAV-POSLLH"):
            lines.append(
                f"    {{{stream.tell() - len(raw)}, {len(raw)}, {msg.lat!r}, {msg.lon!r}, {msg.hMSL / 1000!r}}},"
            )
    lines += [
        "};",
        "struct Satellite { unsigned gnss, id, signal; int elevation, azimuth; bool used; };",
        "inline constexpr Satellite satellites[] = {",
    ]
    sat = UBXReader.parse((ROOT / "nav-sat.ubx").read_bytes())
    for i in range(1, sat.numSvs + 1):
        values = [
            getattr(sat, f"{key}_{i:02}")
            for key in ("gnssId", "svId", "cno", "elev", "azim", "svUsed")
        ]
        lines.append(
            "    {"
            + ", ".join(str(v) for v in values[:-1])
            + ", "
            + str(bool(values[-1])).lower()
            + "},"
        )
    lines += [
        "};",
        "struct Correction { unsigned offset, size, id; };",
        "inline constexpr Correction corrections[] = {",
    ]
    stream = io.BytesIO((ROOT / "mixed.gps").read_bytes())
    for raw, _ in UBXReader(stream, quitonerror=2):
        if raw.startswith(b"\xd3"):
            msg = RTCMReader.parse(raw)
            lines.append(f"    {{{stream.tell() - len(raw)}, {len(raw)}, {msg.identity}}},")
    lines.append("};")
    messages = {
        msg.identity: msg
        for _, msg in SBFReader(io.BytesIO((ROOT / "geodetic.sbf").read_bytes()), quitonerror=2)
    }
    covariance = messages["VelCovGeodetic"]
    lines.append(
        f"inline constexpr double speedVariance = {max(covariance.Cov_VnVn, covariance.Cov_VeVe, covariance.Cov_VuVu)!r};"
    )
    for _, msg in SBFReader(io.BytesIO((ROOT / "attitude.sbf").read_bytes()), quitonerror=2):
        if msg.Error != 128:
            raise RuntimeError("Expected receiver attitude-unavailable fixture")
    relative = UBXReader.parse((ROOT / "relative.ubx").read_bytes())
    lines.append(
        f"inline constexpr bool relativeValid = {str(bool(relative.relPosValid)).lower()};"
    )
    gga = NMEAReader.parse((ROOT / "gga.nmea").read_bytes())
    for name, value in (
        ("ggaLatitude", gga.lat),
        ("ggaLongitude", gga.lon),
        ("ggaAltitude", gga.alt),
        ("ggaSatellites", gga.numSV),
    ):
        lines.append(f"inline constexpr double {name} = {value!r};")
    lines += ["}  // namespace GPSFixture", "// clang-format on", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if checked-in expectations differ"
    )
    args = parser.parse_args()
    output = ROOT / "GPSFixtureExpectations.h"
    expected = generate()
    if args.check:
        if output.read_text() != expected:
            raise SystemExit("Fixture expectations differ; regenerate with the pinned tools")
        print("Pinned fixture expectations match")
    else:
        output.write_text(expected)


if __name__ == "__main__":
    main()
