// Generated by generate_expectations.py; do not edit.
#pragma once

// clang-format off
namespace GPSFixture {
// navigation.ubx: sha256 d931b83094f6698d6245f5bcdadae8a909839abfb6171f5044512a463ddd0d8b
// mixed.gps: sha256 c5fdfea78717ab71c3a28436849276138c90a6e926afd33816c5d6ad047f88d6
// geodetic.sbf: sha256 1080234291a52fe9b61e26287b179ab70b00daf2ca1cadcb4cafa608fca34709
// attitude.sbf: sha256 2d675d380a1c7ba39b9260cdebb027a4d3a14a8ba2363fb4fd3c2372e04c4ffe
// relative.ubx: sha256 7c1d08d64d094c3fd4a444740e54062b2c9ac448121061f79e088a094f60ef18
// gga.nmea: sha256 0230fe6aeb6669ec569922146afe8029f3d1bea016510027ced0df97547bfd51
struct Position { unsigned offset, size; double latitude, longitude, altitude; };
inline constexpr Position positions[] = {
    {0, 100, 53.4507228, -2.2402855, 42.701},
    {1870, 36, 53.4507228, -2.2402855, 42.701},
};
struct Satellite { unsigned gnss, id, signal; int elevation, azimuth; bool used; };
inline constexpr Satellite satellites[] = {
    {0, 2, 31, 18, 221, true},
    {0, 5, 17, 61, 283, true},
    {0, 7, 40, 51, 67, true},
    {0, 9, 0, 15, 89, false},
    {0, 11, 0, 17, 208, false},
    {0, 13, 32, 41, 265, true},
    {0, 14, 0, 14, 146, false},
    {0, 15, 41, 12, 275, true},
    {0, 16, 0, 1, 12, false},
    {0, 18, 30, 12, 331, true},
    {0, 20, 19, 65, 205, true},
    {0, 27, 0, 2, 32, false},
    {0, 30, 41, 71, 128, true},
    {1, 123, 0, 22, 140, false},
    {1, 136, 31, 29, 171, false},
    {2, 2, 0, 33, 135, false},
    {2, 3, 31, 39, 95, true},
    {2, 7, 33, 30, 277, true},
    {2, 8, 37, 84, 294, true},
    {2, 13, 34, 23, 237, true},
    {2, 24, 0, 8, 23, false},
    {2, 25, 29, 38, 72, true},
    {2, 26, 29, 29, 297, true},
    {2, 30, 0, 2, 174, false},
    {2, 33, 26, 9, 342, true},
    {3, 5, 0, 7, 115, false},
    {3, 7, 27, 22, 57, true},
    {3, 10, 0, 24, 72, false},
    {3, 11, 17, 5, 258, false},
    {3, 14, 39, 19, 297, true},
    {3, 21, 29, 79, 145, true},
    {3, 22, 26, 26, 122, true},
    {3, 26, 0, 22, 191, false},
    {3, 28, 28, 10, 332, true},
    {6, 1, 29, 42, 105, true},
    {6, 2, 34, 68, 323, true},
    {6, 3, 31, 17, 298, true},
    {6, 10, 13, 14, 26, false},
    {6, 11, 30, 56, 71, false},
    {6, 12, 26, 39, 163, true},
    {6, 17, 29, 13, 253, true},
    {6, 18, 39, 26, 302, true},
    {6, 19, 0, 16, 349, false},
};
struct Correction { unsigned offset, size, id; };
inline constexpr Correction corrections[] = {
    {52, 25, 1005},
    {77, 68, 4072},
    {145, 275, 1077},
    {420, 201, 1087},
    {621, 151, 1097},
    {772, 275, 1127},
    {1047, 10, 1230},
};
inline constexpr double speedVariance = 4.582880865200423e-05;
inline constexpr bool relativeValid = false;
inline constexpr double ggaLatitude = 53.450657;
inline constexpr double ggaLongitude = -2.2404103333;
inline constexpr double ggaAltitude = 56.0;
inline constexpr double ggaSatellites = 6;
}  // namespace GPSFixture
// clang-format on
