// Generated by generate_expectations.py; do not edit.
#pragma once

#include <limits>

// clang-format off
namespace GPSFixture {
// navigation.ubx: sha256 d931b83094f6698d6245f5bcdadae8a909839abfb6171f5044512a463ddd0d8b
// mixed.gps: sha256 c5fdfea78717ab71c3a28436849276138c90a6e926afd33816c5d6ad047f88d6
// geodetic.sbf: sha256 1080234291a52fe9b61e26287b179ab70b00daf2ca1cadcb4cafa608fca34709
// attitude.sbf: sha256 2d675d380a1c7ba39b9260cdebb027a4d3a14a8ba2363fb4fd3c2372e04c4ffe
// relative.ubx: sha256 7c1d08d64d094c3fd4a444740e54062b2c9ac448121061f79e088a094f60ef18
// gga.nmea: sha256 0230fe6aeb6669ec569922146afe8029f3d1bea016510027ced0df97547bfd51
// synthetic-integrity.ubx: sha256 d9ff3e8b3d2d12a850f2c9be5da616852f3463a52bdcbe40ed3bd40ceadb42dc
// synthetic-timeutc.ubx: sha256 f568418214f6829905c5a31a0393b965fc8502554cee1676262f27a6c84c9e5a
// synthetic-gga.nmea: sha256 ea871d5dc40380020bc73ca8e241a32279416980ec2be9feb8479be8acbb4101
// synthetic-gst.nmea: sha256 fac5d285a1b65b93519ac747eff5de27c657295e93f38319adacba7623c4c884
// synthetic-valid.sbf: sha256 310a9e1c8ab6465be70f8002a59baa1bb68c09bd7afd03a25bb4dcf02e39a969
// synthetic-zero.sbf: sha256 28b5d4f1bd3904c412dcec10968a3a0442990331a8e11be34df0ecf7d49fb6cc
// synthetic-unavailable.sbf: sha256 21fcf9601a73ca6368293183463dc1617c1ae6932dede14300fd1c46642390b3
// synthetic-error.sbf: sha256 c5a7c2bc562dc6b786401ebf56516ba8313db1f5aa61b5a7ff72b852bc4d2137
// synthetic-invalid-time.sbf: sha256 647c6b6ba756ecdabe8432247db11a65cd06cd49c873edb6df2733014786fa44
struct Position { unsigned offset, size; double latitude, longitude, altitude; };
inline constexpr Position positions[] = {
    {0, 100, 53.4507228, -2.2402855, 42.701},
    {1870, 36, 53.4507228, -2.2402855, 42.701},
};
struct Satellite { unsigned gnss, id, signal; int elevation, azimuth; bool used; };
inline constexpr Satellite satellites[] = {
    {0, 2, 31, 18, 221, true},
    {0, 5, 17, 61, 283, true},
    {0, 7, 40, 51, 67, true},
    {0, 9, 0, 15, 89, false},
    {0, 11, 0, 17, 208, false},
    {0, 13, 32, 41, 265, true},
    {0, 14, 0, 14, 146, false},
    {0, 15, 41, 12, 275, true},
    {0, 16, 0, 1, 12, false},
    {0, 18, 30, 12, 331, true},
    {0, 20, 19, 65, 205, true},
    {0, 27, 0, 2, 32, false},
    {0, 30, 41, 71, 128, true},
    {1, 123, 0, 22, 140, false},
    {1, 136, 31, 29, 171, false},
    {2, 2, 0, 33, 135, false},
    {2, 3, 31, 39, 95, true},
    {2, 7, 33, 30, 277, true},
    {2, 8, 37, 84, 294, true},
    {2, 13, 34, 23, 237, true},
    {2, 24, 0, 8, 23, false},
    {2, 25, 29, 38, 72, true},
    {2, 26, 29, 29, 297, true},
    {2, 30, 0, 2, 174, false},
    {2, 33, 26, 9, 342, true},
    {3, 5, 0, 7, 115, false},
    {3, 7, 27, 22, 57, true},
    {3, 10, 0, 24, 72, false},
    {3, 11, 17, 5, 258, false},
    {3, 14, 39, 19, 297, true},
    {3, 21, 29, 79, 145, true},
    {3, 22, 26, 26, 122, true},
    {3, 26, 0, 22, 191, false},
    {3, 28, 28, 10, 332, true},
    {6, 1, 29, 42, 105, true},
    {6, 2, 34, 68, 323, true},
    {6, 3, 31, 17, 298, true},
    {6, 10, 13, 14, 26, false},
    {6, 11, 30, 56, 71, false},
    {6, 12, 26, 39, 163, true},
    {6, 17, 29, 13, 253, true},
    {6, 18, 39, 26, 302, true},
    {6, 19, 0, 16, 349, false},
};
struct Correction { unsigned offset, size, id; };
inline constexpr Correction corrections[] = {
    {52, 25, 1005},
    {77, 68, 4072},
    {145, 275, 1077},
    {420, 201, 1087},
    {621, 151, 1097},
    {772, 275, 1127},
    {1047, 10, 1230},
};
inline constexpr double speedVariance = 4.582880865200423e-05;
inline constexpr bool relativeValid = false;
inline constexpr double ggaLatitude = 53.450657;
inline constexpr double ggaLongitude = -2.2404103333;
inline constexpr double ggaAltitude = 56.0;
inline constexpr double ggaSatellites = 6;
struct Integrity { unsigned offset, size, spoofing, jamming; int noise, agc, indicator, correctionUse, crcFailed; };
inline constexpr Integrity integrity[] = {
    {0, 24, 2, 0, -1, -1, -1, -1, -1},
    {24, 60, 2, 2, 1234, 5678, 91, -1, -1},
    {84, 16, 2, 2, 1234, 5678, 91, 2, 0},
    {100, 16, 2, 2, 1234, 5678, 91, 1, 1},
};
struct Utc { unsigned offset, size; unsigned long long microseconds; };
inline constexpr Utc utc[] = {
    {0, 28, 1709251199750000},
    {28, 28, 0},
    {56, 28, 1709251200125000},
};
struct Gga { unsigned offset, size; const char* talker; double latitude, longitude, altitude, geoid, hdop; unsigned quality; int satellites; };
inline constexpr Gga ggas[] = {
    {0, 71, "GN", 0.0, 0.0, 0.0, 0.0, 0.0, 1, 0},
    {71, 61, "GA", 12.5, -45.25, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 4, -1},
    {132, 77, "GL", -12.5, -45.25, -15.5, -30.25, 0.0, 5, 12},
    {209, 69, "GB", 12.5, 45.25, 0.0, std::numeric_limits<double>::quiet_NaN(), 0.75, 2, 8},
    {278, 71, "GP", 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0},
    {349, 49, "GN", std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 0.0, 0.0, 0.0, 0, -1},
};
struct Gst { unsigned offset, size; const char* talker; double horizontal, vertical; };
inline constexpr Gst gsts[] = {
    {0, 51, "GN", 5.0, 12.0},
    {51, 50, "GA", 0.0, 0.0},
    {101, 44, "GB", std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN()},
};
struct SbfEpoch { const char* filename; double latitude, longitude, ellipsoid, msl, horizontalAccuracy, verticalAccuracy, north, east, down, course, hdop, vdop, speedAccuracy, heading, headingAccuracy; unsigned mode, error, satellites; bool twoDimensional, velocityAvailable; };
inline constexpr SbfEpoch sbfEpochs[] = {
    {"synthetic-valid.sbf", 7.16197243913529, -14.32394487827058, 123.5, 135.75, 0.6, 1.7, -3.0, 4.0, -0.5, 4.71238898038469, 1.25, 2.5, 0.3999999955296516, -1.5707963267948966, 0.026179938779914945, 4, 0, 17, false, true},
    {"synthetic-zero.sbf", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 0, 0, true, true},
    {"synthetic-unavailable.sbf", 7.16197243913529, -14.32394487827058, 123.5, 135.75, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), -20000000000.0, 4.0, -0.5, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 5, 0, 255, false, false},
    {"synthetic-error.sbf", 7.16197243913529, -14.32394487827058, 123.5, 135.75, 0.6, 1.7, -3.0, 4.0, -0.5, 4.71238898038469, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 4, 3, 0, false, false},
};
struct SbfTime { unsigned offset, size, tow, week; };
inline constexpr SbfTime invalidSbfTimes[] = {
    {0, 96, 123000, 65535},
    {96, 96, 4294967295, 2200},
    {192, 96, 604800000, 2200},
};
}  // namespace GPSFixture

// clang-format on
