/* This file was generated by syncqt. */
#ifndef QT_QTTOOLS_VERSION_H
#define QT_QTTOOLS_VERSION_H

#define QTTOOLS_VERSION_STR "6.10.3"

#define QTTOOLS_VERSION 0x0601003

#endif // QT_QTTOOLS_VERSION_H
