#pragma once

#include <stdint.h>

enum PX4_CUSTOM_MAIN_MODE {
	PX4_CUSTOM_MAIN_MODE_MANUAL = 1,
	PX4_CUSTOM_MAIN_MODE_ALTCTL = 2,
	PX4_CUSTOM_MAIN_MODE_POSCTL = 3,
	PX4_CUSTOM_MAIN_MODE_AUTO = 4,
	PX4_CUSTOM_MAIN_MODE_ACRO = 5,
	PX4_CUSTOM_MAIN_MODE_OFFBOARD = 6,
	PX4_CUSTOM_MAIN_MODE_STABILIZED = 7,
	PX4_CUSTOM_MAIN_MODE_RATTITUDE_DEPRECATED = 8,
	PX4_CUSTOM_MAIN_MODE_SIMPLE = 9, /* unused, but reserved for future use */
	PX4_CUSTOM_MAIN_MODE_TERMINATION = 10,
	PX4_CUSTOM_MAIN_MODE_ALTITUDE_CRUISE = 11
};

enum PX4_CUSTOM_SUB_MODE_AUTO {
	PX4_CUSTOM_SUB_MODE_AUTO_READY = 1,
	PX4_CUSTOM_SUB_MODE_AUTO_TAKEOFF = 2,
	PX4_CUSTOM_SUB_MODE_AUTO_LOITER = 3,
	PX4_CUSTOM_SUB_MODE_AUTO_MISSION = 4,
	PX4_CUSTOM_SUB_MODE_AUTO_RTL = 5,
	PX4_CUSTOM_SUB_MODE_AUTO_LAND = 6,
	PX4_CUSTOM_SUB_MODE_AUTO_RESERVED_DO_NOT_USE = 7, // was PX4_CUSTOM_SUB_MODE_AUTO_RTGS, deleted 2020-03-05
	PX4_CUSTOM_SUB_MODE_AUTO_FOLLOW_TARGET = 8,
	PX4_CUSTOM_SUB_MODE_AUTO_PRECLAND = 9,
	PX4_CUSTOM_SUB_MODE_AUTO_VTOL_TAKEOFF = 10,
	PX4_CUSTOM_SUB_MODE_GUIDED_COURSE = 11,
};

enum PX4_CUSTOM_SUB_MODE_POSCTL {
    PX4_CUSTOM_SUB_MODE_POSCTL_POSCTL = 0,
    PX4_CUSTOM_SUB_MODE_POSCTL_ORBIT = 1,
    PX4_CUSTOM_SUB_MODE_POSCTL_SLOW = 2
};

union px4_custom_mode {
    struct {
        uint16_t reserved;
        uint8_t main_mode;
        uint8_t sub_mode;
    };
    uint32_t data;
    float data_float;
    struct {
        uint16_t reserved_hl;
        uint16_t custom_mode_hl;
    };
};

struct PX4CustomMode{
    enum Mode : uint32_t{
        MANUAL              = PX4_CUSTOM_MAIN_MODE_MANUAL          <<16,
        STABILIZED          = PX4_CUSTOM_MAIN_MODE_STABILIZED      <<16,
        ACRO                = PX4_CUSTOM_MAIN_MODE_ACRO            <<16,
        RATTITUDE           = PX4_CUSTOM_MAIN_MODE_RATTITUDE_DEPRECATED <<16,
        ALTCTL              = PX4_CUSTOM_MAIN_MODE_ALTCTL          <<16,
        OFFBOARD            = PX4_CUSTOM_MAIN_MODE_OFFBOARD        <<16,
        SIMPLE              = PX4_CUSTOM_MAIN_MODE_SIMPLE          <<16,
        TERMINATION         = PX4_CUSTOM_MAIN_MODE_TERMINATION     <<16,
        ALTITUDE_CRUISE     = PX4_CUSTOM_MAIN_MODE_ALTITUDE_CRUISE <<16,
        POSCTL_POSCTL       = PX4_CUSTOM_MAIN_MODE_POSCTL       <<16 | (PX4_CUSTOM_SUB_MODE_POSCTL_POSCTL      << 24 ),
        POSCTL_ORBIT        = PX4_CUSTOM_MAIN_MODE_POSCTL       <<16 | (PX4_CUSTOM_SUB_MODE_POSCTL_ORBIT       << 24 ),
        POSCTL_SLOW         = PX4_CUSTOM_MAIN_MODE_POSCTL       <<16 | (PX4_CUSTOM_SUB_MODE_POSCTL_SLOW        << 24 ),
        AUTO_LOITER         = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_LOITER        << 24 ),
        AUTO_MISSION        = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_MISSION       << 24 ),
        AUTO_RTL            = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_RTL           << 24 ),
        AUTO_FOLLOW_TARGET  = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_FOLLOW_TARGET << 24 ),
        AUTO_LAND           = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_LAND          << 24 ),
        AUTO_PRECLAND       = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_PRECLAND      << 24 ),
        AUTO_READY          = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_READY         << 24 ),
        AUTO_TAKEOFF        = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_TAKEOFF       << 24 ),
        AUTO_VTOL_TAKEOFF   = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_VTOL_TAKEOFF  << 24 ),
        AUTO_GUIDED_COURSE  = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_GUIDED_COURSE      << 24 ),
    };
};
