name: Build GStreamer
description: Build GStreamer from source for QGC video streaming
inputs:
  version:
    description: GStreamer version (use build-config.outputs.gstreamer_version)
    required: true
  build-type:
    description: Build type (release or debug)
    required: false
    default: release
  work-dir:
    description: Working directory for source
    required: false
    default: ${{ runner.temp }}
  prefix:
    description: Install prefix
    required: false
    default: ${{ runner.temp }}/gst
runs:
  using: composite
  steps:
    - name: Build GStreamer
      shell: bash
      run: |
        "${{ github.workspace }}/tools/setup/build-gstreamer.sh" \
          --version "${{ inputs.version }}" \
          --type "${{ inputs.build-type }}" \
          --work-dir "${{ inputs.work-dir }}" \
          --prefix "${{ inputs.prefix }}"

    - name: Setup Environment
      shell: bash
      run: |
        ARCH=$(uname -m)
        case "$ARCH" in
            x86_64)  ARCH_DIR="x86_64-linux-gnu" ;;
            aarch64) ARCH_DIR="aarch64-linux-gnu" ;;
            armv7l)  ARCH_DIR="arm-linux-gnueabihf" ;;
            *)       ARCH_DIR="$ARCH-linux-gnu" ;;
        esac
        echo "PKG_CONFIG_PATH=${{ inputs.prefix }}/lib/$ARCH_DIR/pkgconfig:$PKG_CONFIG_PATH" >> "$GITHUB_ENV"
        echo "GST_PLUGIN_PATH=${{ inputs.prefix }}/lib/$ARCH_DIR/gstreamer-1.0" >> "$GITHUB_ENV"

    - name: Save artifact
      uses: actions/upload-artifact@v6
      with:
        name: GStreamer-${{ inputs.build-type }}
        path: ${{ inputs.prefix }}
