/* Generated by configure. Do not edit */
#ifndef PANGO_FEATURES_H
#define PANGO_FEATURES_H

#define PANGO_VERSION_MAJOR 1
#define PANGO_VERSION_MINOR 36
#define PANGO_VERSION_MICRO 8

#define PANGO_VERSION_STRING "1.36.8"


#endif
