name: Download All Platform Artifacts
description: Download artifacts from all completed platform workflow runs for the same commit

inputs:
  github-token:
    description: GitHub token for API access
    required: true

runs:
  using: composite
  steps:
    - name: Download artifacts from all platform workflows
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        python3 "${GITHUB_WORKSPACE}/tools/setup/download_artifacts.py" \
          --repo "${{ github.repository }}" \
          --head-sha "${{ github.event.workflow_run.head_sha }}" \
          --output-dir artifacts \
          --workflows "Linux,Windows,MacOS,Android"
