name: Build Config
description: Read build toolchain versions from .github/build-config.json

outputs:
  qt_version:
    description: Qt version
    value: ${{ steps.read.outputs.qt_version }}
  qt_modules:
    description: Qt modules (desktop)
    value: ${{ steps.read.outputs.qt_modules }}
  qt_modules_ios:
    description: Qt modules (iOS, excludes qtserialport/qtscxml)
    value: ${{ steps.read.outputs.qt_modules_ios }}
  gstreamer_windows_version:
    description: GStreamer version (Windows)
    value: ${{ steps.read.outputs.gstreamer_windows_version }}
  ndk_full_version:
    description: Android NDK version (full form for sdkmanager)
    value: ${{ steps.read.outputs.ndk_full_version }}
  java_version:
    description: Java version
    value: ${{ steps.read.outputs.java_version }}
  android_platform:
    description: Android platform/API level
    value: ${{ steps.read.outputs.android_platform }}
  android_build_tools:
    description: Android build tools version
    value: ${{ steps.read.outputs.android_build_tools }}
  android_cmdline_tools:
    description: Android command line tools version
    value: ${{ steps.read.outputs.android_cmdline_tools }}
  xcode_version:
    description: Xcode version (macOS)
    value: ${{ steps.read.outputs.xcode_version }}
  xcode_ios_version:
    description: Xcode version (iOS)
    value: ${{ steps.read.outputs.xcode_ios_version }}

runs:
  using: composite
  steps:
    - name: Read build config
      id: read
      shell: bash
      run: |
        if command -v python3 >/dev/null 2>&1; then
          py_cmd="python3"
        else
          py_cmd="python"
        fi
        "${py_cmd}" ./tools/setup/read_config.py --github-output
