#include "FlightModeSettings.h"

DECLARE_SETTINGGROUP(FlightMode, "FlightMode")
{
}

DECLARE_SETTINGSFACT(FlightModeSettings, px4HiddenFlightModesMultiRotor)
DECLARE_SETTINGSFACT(FlightModeSettings, px4HiddenFlightModesFixedWing)
DECLARE_SETTINGSFACT(FlightModeSettings, px4HiddenFlightModesVTOL)
DECLARE_SETTINGSFACT(FlightModeSettings, px4HiddenFlightModesRoverBoat)
DECLARE_SETTINGSFACT(FlightModeSettings, px4HiddenFlightModesSub)
DECLARE_SETTINGSFACT(FlightModeSettings, px4HiddenFlightModesAirship)
DECLARE_SETTINGSFACT(FlightModeSettings, apmHiddenFlightModesMultiRotor)
DECLARE_SETTINGSFACT(FlightModeSettings, apmHiddenFlightModesFixedWing)
DECLARE_SETTINGSFACT(FlightModeSettings, apmHiddenFlightModesVTOL)
DECLARE_SETTINGSFACT(FlightModeSettings, apmHiddenFlightModesRoverBoat)
DECLARE_SETTINGSFACT(FlightModeSettings, apmHiddenFlightModesSub)
DECLARE_SETTINGSFACT(FlightModeSettings, apmHiddenFlightModesAirship)
DECLARE_SETTINGSFACT(FlightModeSettings, requireModeChangeConfirmation)
