# shellcheck shell=bash
# Seeds the minimal pacman packages + locale to run install_dependencies
# (--platform arch) and the uv venv.
# Arch's /bin/sh is bash, so pipefail is available even when run as `sh`.
set -euo pipefail

# Refresh the keyring before -Su: BASE_REF is digest-pinned, so the bundled
# archlinux-keyring ages out and -Su fails signature checks without this.
pacman -Sy --noconfirm --needed archlinux-keyring
pacman -Su --noconfirm --needed ca-certificates git python

# Enable the en_US.UTF-8 locale (Arch ships none generated by default).
sed -i 's/^# *\(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen
locale-gen

# Drop the package cache to keep the image layer small.
pacman -Scc --noconfirm
