include(CheckCompilerFlag)
include(CheckLinkerFlag)
include(CMakePushCheckState)

option(QGC_ENABLE_HARDENING "Apply security hardening flags to non-Debug builds" ON)
option(QGC_REPRODUCIBLE_BUILD "Strip build paths from non-Debug binaries (-ffile-prefix-map)" ON)

function(_qgc_try_compile_flag flag out_var)
    string(MAKE_C_IDENTIFIER "QGC_HARDEN_CXX_${flag}" _probe)
    cmake_push_check_state(RESET)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        set(CMAKE_REQUIRED_FLAGS "-Werror=unused-command-line-argument")
    endif()
    check_compiler_flag(CXX "${flag}" ${_probe})
    cmake_pop_check_state()
    if(${_probe})
        set(_acc ${${out_var}})
        list(APPEND _acc "${flag}")
        set(${out_var} "${_acc}" PARENT_SCOPE)
    endif()
endfunction()

function(_qgc_try_link_flag flag out_var)
    string(MAKE_C_IDENTIFIER "QGC_HARDEN_LD_${flag}" _probe)
    cmake_push_check_state(RESET)
    check_linker_flag(CXX "${flag}" ${_probe})
    cmake_pop_check_state()
    if(${_probe})
        set(_acc ${${out_var}})
        list(APPEND _acc "${flag}")
        set(${out_var} "${_acc}" PARENT_SCOPE)
    endif()
endfunction()

function(qgc_apply_global_hardening)
    list(APPEND CMAKE_MESSAGE_CONTEXT hardening)
    set(_cxx "")
    set(_link "")

    if(QGC_ENABLE_HARDENING)
        if(MSVC)
            _qgc_try_compile_flag("/guard:cf" _cxx)
            _qgc_try_link_flag("/guard:cf" _link)
            _qgc_try_link_flag("/DYNAMICBASE" _link)
            _qgc_try_link_flag("/HIGHENTROPYVA" _link)
            _qgc_try_link_flag("/NXCOMPAT" _link)
        else()
            list(APPEND _cxx "-U_FORTIFY_SOURCE" "-D_FORTIFY_SOURCE=3")
            _qgc_try_compile_flag("-fstack-protector-strong" _cxx)
            _qgc_try_compile_flag("-fstack-clash-protection" _cxx)
            if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|i[0-9]86|x86")
                _qgc_try_compile_flag("-fcf-protection=full" _cxx)
            elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
                # AArch64 only: clang rejects -mbranch-protection on 32-bit ARM/Thumb (e.g. armeabi-v7a)
                _qgc_try_compile_flag("-mbranch-protection=standard" _cxx)
            endif()
            _qgc_try_link_flag("-Wl,-z,relro" _link)
            _qgc_try_link_flag("-Wl,-z,now" _link)
            _qgc_try_link_flag("-Wl,-z,noexecstack" _link)
        endif()
    endif()

    if(QGC_REPRODUCIBLE_BUILD AND NOT MSVC)
        _qgc_try_compile_flag("-ffile-prefix-map=${CMAKE_SOURCE_DIR}=." _cxx)
        _qgc_try_compile_flag("-ffile-prefix-map=${CMAKE_BINARY_DIR}=./build" _cxx)
        if(CPM_SOURCE_CACHE)
            _qgc_try_compile_flag("-ffile-prefix-map=${CPM_SOURCE_CACHE}=./.cpm" _cxx)
        endif()
    endif()

    foreach(_flag IN LISTS _cxx)
        add_compile_options("$<$<NOT:$<CONFIG:Debug>>:${_flag}>")
    endforeach()
    foreach(_flag IN LISTS _link)
        add_link_options("$<$<NOT:$<CONFIG:Debug>>:${_flag}>")
    endforeach()

    set(QGC_HARDENING_CXX_FLAGS "${_cxx}" CACHE INTERNAL "Applied hardening/reproducible compile flags")
    set(QGC_HARDENING_LINK_FLAGS "${_link}" CACHE INTERNAL "Applied hardening link flags")

    list(LENGTH _cxx _n_cxx)
    list(LENGTH _link _n_link)
    message(STATUS "QGC: Hardening — ${_n_cxx} compile flag(s), ${_n_link} link flag(s) (non-Debug configs)")
endfunction()
