# Copyright (C) 2024 The Qt Company Ltd.
# SPDX-License-Identifier: BSD-3-Clause

set(QT_SUPPORTED_MIN_CMAKE_VERSION_FOR_USING_QT "3.22")
set(QT_COMPUTED_MIN_CMAKE_VERSION_FOR_USING_QT "3.22")


if(NOT QT_SUPPORTED_MIN_IOS_SDK_VERSION)
    set(QT_SUPPORTED_MIN_IOS_SDK_VERSION "17")
endif()

if(NOT QT_SUPPORTED_MAX_IOS_SDK_VERSION)
    set(QT_SUPPORTED_MAX_IOS_SDK_VERSION "26")
endif()

if(NOT QT_SUPPORTED_MIN_IOS_XCODE_VERSION)
    set(QT_SUPPORTED_MIN_IOS_XCODE_VERSION "15")
endif()

if(NOT QT_SUPPORTED_MIN_IOS_VERSION)
    set(QT_SUPPORTED_MIN_IOS_VERSION "17")
endif()

if(NOT QT_SUPPORTED_MAX_IOS_VERSION_TESTED)
    set(QT_SUPPORTED_MAX_IOS_VERSION_TESTED "26")
endif()

if(NOT QT_SUPPORTED_MIN_VISIONOS_SDK_VERSION)
    set(QT_SUPPORTED_MIN_VISIONOS_SDK_VERSION "1")
endif()

if(NOT QT_SUPPORTED_MAX_VISIONOS_SDK_VERSION)
    set(QT_SUPPORTED_MAX_VISIONOS_SDK_VERSION "2")
endif()

if(NOT QT_SUPPORTED_MIN_VISIONOS_XCODE_VERSION)
    set(QT_SUPPORTED_MIN_VISIONOS_XCODE_VERSION "15")
endif()

if(NOT QT_SUPPORTED_MIN_VISIONOS_VERSION)
    set(QT_SUPPORTED_MIN_VISIONOS_VERSION "1")
endif()

if(NOT QT_SUPPORTED_MAX_VISIONOS_VERSION_TESTED)
    set(QT_SUPPORTED_MAX_VISIONOS_VERSION_TESTED "2")
endif()

if(NOT QT_SUPPORTED_MIN_MACOS_SDK_VERSION)
    set(QT_SUPPORTED_MIN_MACOS_SDK_VERSION "14")
endif()

if(NOT QT_SUPPORTED_MAX_MACOS_SDK_VERSION)
    set(QT_SUPPORTED_MAX_MACOS_SDK_VERSION "26")
endif()

if(NOT QT_SUPPORTED_MIN_MACOS_XCODE_VERSION)
    set(QT_SUPPORTED_MIN_MACOS_XCODE_VERSION "15")
endif()

if(NOT QT_SUPPORTED_MIN_MACOS_VERSION)
    set(QT_SUPPORTED_MIN_MACOS_VERSION "13")
endif()

if(NOT QT_SUPPORTED_MAX_MACOS_VERSION_TESTED)
    set(QT_SUPPORTED_MAX_MACOS_VERSION_TESTED "26")
endif()
