#!/bin/bash
# QGroundControl Development Environment Setup Script
# Automates initial setup for contributors

set -e

echo "================================================"
echo "QGroundControl Development Environment Setup"
echo "================================================"
echo ""

# Detect OS
OS="unknown"
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    OS="linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    OS="macos"
else
    echo "Unsupported OS: $OSTYPE"
    exit 1
fi

echo "Detected OS: $OS"
echo ""

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check prerequisites
echo "Checking prerequisites..."
MISSING_DEPS=()

if ! command_exists git; then
    MISSING_DEPS+=("git")
fi

if ! command_exists cmake; then
    MISSING_DEPS+=("cmake")
fi

if ! command_exists ninja; then
    MISSING_DEPS+=("ninja")
fi

if ! command_exists python3; then
    MISSING_DEPS+=("python3")
fi

if [ ${#MISSING_DEPS[@]} -ne 0 ]; then
    echo "ERROR: Missing required dependencies: ${MISSING_DEPS[*]}"
    echo ""
    if [ "$OS" = "linux" ]; then
        echo "Install with: sudo apt install ${MISSING_DEPS[*]}"
    elif [ "$OS" = "macos" ]; then
        echo "Install with: brew install ${MISSING_DEPS[*]}"
    fi
    exit 1
fi

echo "✓ All prerequisites installed"
echo ""

# Initialize git submodules
echo "Initializing git submodules..."
if git submodule update --init --recursive; then
    echo "✓ Submodules initialized"
else
    echo "✗ Failed to initialize submodules"
    exit 1
fi
echo ""

# Install pre-commit hooks
echo "Setting up pre-commit hooks..."
if command_exists pre-commit; then
    echo "✓ pre-commit already installed"
else
    echo "Installing pre-commit..."
    if python3 -m pip install --user pre-commit; then
        echo "✓ pre-commit installed"
    else
        echo "⚠ Failed to install pre-commit (optional)"
    fi
fi

if command_exists pre-commit; then
    if pre-commit install; then
        echo "✓ Pre-commit hooks installed"
    else
        echo "⚠ Failed to install pre-commit hooks (optional)"
    fi
fi
echo ""

# Install cmake-format (optional)
echo "Setting up cmake-format (optional)..."
if python3 -m pip install --user cmake-format 2>/dev/null; then
    echo "✓ cmake-format installed"
else
    echo "⚠ cmake-format installation skipped (optional)"
fi
echo ""

# Note: .qmlls.ini is auto-generated by CMake (QT_QML_GENERATE_QMLLS_INI=ON)

# Check for Qt installation
echo "Checking for Qt 6.10.0..."
QT_FOUND=false
if [ "$OS" = "linux" ]; then
    QT_PATHS=("$HOME/Qt/6.10.0/gcc_64" "/opt/Qt/6.10.0/gcc_64")
elif [ "$OS" = "macos" ]; then
    QT_PATHS=("$HOME/Qt/6.10.0/macos" "$HOME/Qt/6.10.0/clang_64")
fi

for path in "${QT_PATHS[@]}"; do
    if [ -d "$path" ]; then
        echo "✓ Found Qt at: $path"
        QT_FOUND=true
        QT_PATH="$path"
        break
    fi
done

if [ "$QT_FOUND" = false ]; then
    echo "⚠ Qt 6.10.0 not found in standard locations"
    echo "  Install from: https://www.qt.io/download-qt-installer"
else
    echo ""
    echo "You can now build with:"
    echo "  $QT_PATH/bin/qt-cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug"
    echo "  cmake --build build -j\$(nproc)"
fi

echo ""
echo "================================================"
echo "Setup complete! Next steps:"
echo "================================================"
echo "1. Install Qt 6.10.0 if not already installed"
echo "2. Build: ./tools/quick-build.sh"
echo "3. Read: QUICKSTART.md for development guide"
echo ""
