"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "../docs"

"preserve_hierarchy": true

"files": [
  {
    "source": "/en/**/*.md",
    "translation": "/%two_letters_code%/**/%original_file_name%"
  }
]
