qgc_add_gps_component(QGCGPSRecording COMPONENT Recording LOGGING_TARGET QGCLogging)

qgc_gps_component_sources(recording_controller_sources RecordingController)
target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${recording_controller_sources})
target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE QGCGPSRecording)
