name: Run Qt Tests
description: Run QGroundControl unit tests with proper display handling

inputs:
  binary-path:
    description: 'Path to QGroundControl binary (auto-detected if not specified)'
    required: false
  build-dir:
    description: 'Build directory (for auto-detection)'
    required: false
    default: 'build'
  build-type:
    description: 'Build type for binary location'
    required: false
    default: 'Debug'
  output-file:
    description: 'JUnit XML output file'
    required: false
    default: 'junit-results.xml'
  log-file:
    description: 'Test output log file'
    required: false
    default: 'test-output.txt'
  test-filter:
    description: 'Test filter (passed to --unittest:FILTER)'
    required: false
    default: ''
  timeout:
    description: 'Test timeout in seconds'
    required: false
    default: '300'
  platform:
    description: 'Qt platform plugin (offscreen for headless)'
    required: false
    default: 'offscreen'

outputs:
  exit_code:
    description: 'Test exit code'
    value: ${{ steps.run.outputs.exit_code }}
  passed:
    description: 'Whether tests passed (true/false)'
    value: ${{ steps.run.outputs.passed }}
  log_file:
    description: 'Path to test log'
    value: ${{ steps.run.outputs.log_file }}

runs:
  using: composite
  steps:
    - name: Run tests
      id: run
      shell: bash
      run: |
        args=(
          -B "${{ inputs.build-dir }}"
          -t "${{ inputs.build-type }}"
          --timeout "${{ inputs.timeout }}"
          --xml
          --output "${{ inputs.build-dir }}/${{ inputs.output-file }}"
          --log-file "${{ inputs.build-dir }}/${{ inputs.log-file }}"
          -v
        )

        # Add binary path if specified
        [[ -n "${{ inputs.binary-path }}" ]] && args+=(--binary "${{ inputs.binary-path }}")

        # Add test filter if specified
        [[ -n "${{ inputs.test-filter }}" ]] && args+=(--filter "${{ inputs.test-filter }}")

        # Add headless mode if platform is offscreen
        [[ "${{ inputs.platform }}" == "offscreen" ]] && args+=(--headless)

        # Run tests (exit code handled by the script)
        if command -v python3 >/dev/null 2>&1; then
          py_cmd="python3"
        else
          py_cmd="python"
        fi
        "${py_cmd}" "${{ github.workspace }}/tools/run_tests.py" "${args[@]}" || exit_code=$?

        # Script writes to GITHUB_OUTPUT, propagate exit code
        exit ${exit_code:-0}
