include(CPackIFW)

set(CPACK_GENERATOR "IFW")
set(CPACK_IFW_VERBOSE ON)

set(CPACK_IFW_ROOT "${Qt6_ROOT_DIR}/../../Tools/QtInstallerFramework/4.8")

if(${CMAKE_SYSTEM_NAME} MATCHES Linux)
    set(CPACK_IFW_TARGET_DIRECTORY "@HomeDir@/${QGC_APP_NAME}")
elseif(${CMAKE_SYSTEM_NAME} MATCHES Windows)
    set(CPACK_IFW_TARGET_DIRECTORY "@HomeDir@\\${QGC_APP_NAME}")
elseif(${CMAKE_SYSTEM_NAME} MATCHES Darwin)
    set(CPACK_IFW_TARGET_DIRECTORY "@ApplicationsDir@/${QGC_APP_NAME}")
    set(CPACK_IFW_ADMIN_TARGET_DIRECTORY "@ApplicationsDir@/${QGC_APP_NAME}")
endif()

set(CPACK_IFW_PACKAGE_NAME "${QGC_APP_NAME}")
set(CPACK_IFW_PACKAGE_TITLE "${QGC_INSTALLER_NAME}")
set(CPACK_IFW_PACKAGE_TITLE_COLOR "#007A5C")
set(CPACK_IFW_PACKAGE_ICON "${QGC_APP_ICON}")
set(CPACK_IFW_PACKAGE_PUBLISHER "${QGC_ORG_NAME}")
set(CPACK_IFW_PACKAGE_WIZARD_STYLE "Modern")
set(CPACK_IFW_PACKAGE_LOGO "${CMAKE_SOURCE_DIR}/resources/QGCLogoFull.svg")
set(CPACK_IFW_PACKAGE_WINDOW_ICON "${CMAKE_SOURCE_DIR}/resources/icons/qgroundcontrol.png")
set(CPACK_IFW_PACKAGE_WIZARD_SHOW_PAGE_LIST OFF)
set(CPACK_IFW_PACKAGE_RUN_PROGRAM "@TargetDir@/${QGC_APP_NAME}")
set(CPACK_IFW_PACKAGE_RUN_PROGRAM_DESCRIPTION "Start ${QGC_APP_NAME}")
set(CPACK_IFW_PACKAGE_STYLE_SHEET ${INSTALLER_ROOT}/config/dev/style.qss)
set(CPACK_IFW_PACKAGE_WATERMARK ${INSTALLER_ROOT}/config/qgroundcontrol.png)
set(CPACK_IFW_PACKAGE_MAINTENANCE_TOOL_NAME "${QGC_APP_NAME}-install-tool")
set(CPACK_IFW_PACKAGE_MAINTENANCE_TOOL_INI_FILE "${QGC_APP_NAME}-install-tool.ini")
set(CPACK_IFW_PACKAGE_ALLOW_NON_ASCII_CHARACTERS OFF)

set(CPACK_IFW_PRODUCT_URL "${CMAKE_PROJECT_HOMEPAGE_URL}")

cpack_ifw_configure_component(${QGC_APP_NAME}
    ESSENTIAL FORCED_INSTALLATION
    NAME ${QGC_APP_NAME}
    VERSION ${QGC_APP_VERSION}
    DESCRIPTION "Welcome to the ${QGC_APP_NAME} installer."
    LICENSES "GPL LICENSE" ${CPACK_RESOURCE_FILE_LICENSE}
    SCRIPT "${CMAKE_SOURCE_DIR}/deploy/installer/packages/org.mavlink.qgroundcontrol/meta/dev/installerscript.qs"
)
