include(CreateCPackCommon)

set(CPACK_GENERATOR "ZIP")

set(CPACK_ARCHIVE_FILE_NAME ${CPACK_PACKAGE_FILE_NAME})
set(CPACK_ARCHIVE_FILE_EXTENSION TXZ)
set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_ARCHIVE_THREADS 2)

include(CPack)
