set(GST_VERSION "1.24.2")
if(ANDROID)
	set(GST_URL https://gstreamer.freedesktop.org/data/pkg/android/${GST_VERSION}/gstreamer-1.0-android-universal-${GST_VERSION}.tar.xz)
	set(GST_ZIP_PATH ${CMAKE_SOURCE_DIR}/gstreamer-1.0-android-universal.tar.xz)
	set(GST_TARGET_PATH ${CMAKE_SOURCE_DIR}/gstreamer-1.0-android-universal)
	if(NOT EXISTS "${GST_TARGET_PATH}")
		file(DOWNLOAD ${GST_URL} ${GST_ZIP_PATH})
		execute_process(COMMAND mkdir gstreamer-1.0-android-universal)
		execute_process(COMMAND tar xf ${GST_ZIP_PATH} -C ${GST_TARGET_PATH})
	endif()
endif()
