# QGroundControl Build Configuration Summary

string(TIMESTAMP QGC_CONFIGURE_TIME "%Y-%m-%d %H:%M:%S %Z")

function(_qgc_kv _label _value)
    if(NOT "${_value}" STREQUAL "")
        message(STATUS "  ${_label}${_value}")
    endif()
endfunction()

macro(OptionOutput _label)
    if(${ARGN})
        set(_val "ON")
    else()
        set(_val "OFF")
    endif()
    message(STATUS "  ${_label}: ${_val}")
endmacro()

message(STATUS "")
message(STATUS "==================================================================")
message(STATUS "QGroundControl Build Configuration Summary")
message(STATUS "  Reporting a build problem? Copy this entire block into your issue")
message(STATUS "  at https://github.com/mavlink/qgroundcontrol/issues")
message(STATUS "==================================================================")

message(STATUS "")
message(STATUS "Version & Source:")
_qgc_kv("Version:            " "${QGC_APP_VERSION_STR}")
_qgc_kv("Branch:             " "${QGC_GIT_BRANCH}")
_qgc_kv("Commit:             " "${QGC_GIT_HASH}")
if(QGC_GIT_DIRTY)
    message(STATUS "  Working tree:       DIRTY (uncommitted changes present)")
else()
    message(STATUS "  Working tree:       clean")
endif()
_qgc_kv("Configured at:      " "${QGC_CONFIGURE_TIME}")

message(STATUS "")
message(STATUS "CMake System:")
_qgc_kv("CMake version:      " "${CMAKE_VERSION}")
_qgc_kv("Generator:          " "${CMAKE_GENERATOR}")
_qgc_kv("Make program:       " "${CMAKE_MAKE_PROGRAM}")
if(CMAKE_CONFIGURATION_TYPES)
    _qgc_kv("Configurations:     " "${CMAKE_CONFIGURATION_TYPES}")
else()
    _qgc_kv("Build type:         " "${CMAKE_BUILD_TYPE}")
endif()
_qgc_kv("Source directory:   " "${CMAKE_SOURCE_DIR}")
_qgc_kv("Binary directory:   " "${CMAKE_BINARY_DIR}")
_qgc_kv("Install prefix:     " "${CMAKE_INSTALL_PREFIX}")
message(STATUS "  Host system:        ${CMAKE_HOST_SYSTEM_NAME} ${CMAKE_HOST_SYSTEM_VERSION} (${CMAKE_HOST_SYSTEM_PROCESSOR})")
message(STATUS "  Target system:      ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_VERSION} (${CMAKE_SYSTEM_PROCESSOR})")
if(LINUX AND DEFINED QGC_LINUX_DISTRO)
    _qgc_kv("Linux distro:       " "${QGC_LINUX_DISTRO} (family: ${QGC_LINUX_DISTRO_FAMILY})")
endif()
_qgc_kv("Toolchain file:     " "${CMAKE_TOOLCHAIN_FILE}")
_qgc_kv("Prefix path:        " "${CMAKE_PREFIX_PATH}")

message(STATUS "")
message(STATUS "Compiler & Linker:")
message(STATUS "  C++ compiler:       ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
_qgc_kv("Compiler path:      " "${CMAKE_CXX_COMPILER}")
message(STATUS "  C++ standard:       C++${CMAKE_CXX_STANDARD}")
_qgc_kv("Compiler flags:     " "${CMAKE_CXX_FLAGS}")
_qgc_kv("Linker flags:       " "${CMAKE_EXE_LINKER_FLAGS}")
if(QGC_LINKER)
    message(STATUS "  Linker:             ${QGC_LINKER}")
else()
    message(STATUS "  Linker:             system default")
endif()
if(CMAKE_INTERPROCEDURAL_OPTIMIZATION)
    message(STATUS "  IPO/LTO:            ON")
else()
    message(STATUS "  IPO/LTO:            OFF")
endif()
if(QGC_SPLIT_DWARF_ACTIVE)
    if(QGC_SPLIT_DWARF_GDB_INDEX)
        message(STATUS "  Split-DWARF:        ON (with --gdb-index)")
    else()
        message(STATUS "  Split-DWARF:        ON (no --gdb-index)")
    endif()
else()
    message(STATUS "  Split-DWARF:        OFF")
endif()
if(QGC_CACHE_PROGRAM)
    get_filename_component(_cache_tool "${QGC_CACHE_PROGRAM}" NAME_WE)
    message(STATUS "  Build cache:        ${_cache_tool} (${QGC_CACHE_PROGRAM})")
else()
    message(STATUS "  Build cache:        none")
endif()
list(LENGTH QGC_HARDENING_CXX_FLAGS _qgc_n_harden_cxx)
list(LENGTH QGC_HARDENING_LINK_FLAGS _qgc_n_harden_link)
if(_qgc_n_harden_cxx GREATER 0 OR _qgc_n_harden_link GREATER 0)
    message(STATUS "  Hardening:          ${_qgc_n_harden_cxx} compile + ${_qgc_n_harden_link} link flag(s), non-Debug")
else()
    message(STATUS "  Hardening:          OFF")
endif()
if(QGC_REPRODUCIBLE_BUILD)
    message(STATUS "  Reproducible paths: ON (stripped from non-Debug binaries)")
else()
    message(STATUS "  Reproducible paths: OFF")
endif()

message(STATUS "")
message(STATUS "Qt & Python:")
_qgc_kv("Qt version:         " "${Qt6_VERSION}")
_qgc_kv("Qt location:        " "${Qt6_DIR}")
_qgc_kv("Qt host path:       " "${QT_HOST_PATH}")
_qgc_kv("Python:             " "${Python3_EXECUTABLE}")
_qgc_kv("Python version:     " "${Python3_VERSION}")

# Application Metadata
message(STATUS "")
message(STATUS "Application:")
_qgc_kv("Name:               " "${QGC_APP_NAME}")
_qgc_kv("Version:            " "${QGC_APP_VERSION_STR}")
_qgc_kv("Description:        " "${QGC_APP_DESCRIPTION}")
message(STATUS "  Organization:       ${QGC_ORG_NAME} (${QGC_ORG_DOMAIN})")
_qgc_kv("Package name:       " "${QGC_PACKAGE_NAME}")
_qgc_kv("Settings version:   " "${QGC_SETTINGS_VERSION}")

# Build & Feature Flags
message(STATUS "")
message(STATUS "Build & Feature Flags:")
OptionOutput("Stable build                          " QGC_STABLE_BUILD)
OptionOutput("Use build caching                     " QGC_USE_CACHE)
OptionOutput("Unity build                           " QGC_UNITY_BUILD)
OptionOutput("Enable testing                        " QGC_BUILD_TESTING)
OptionOutput("Enable QML debugging                  " QGC_DEBUG_QML)
OptionOutput("Enable QML linting                    " QT_QML_GENERATE_QMLLINT)
OptionOutput("Disable serial links                  " QGC_NO_SERIAL_LINK)
OptionOutput("Enable GStreamer video                " QGC_ENABLE_GST_VIDEOSTREAMING)
OptionOutput("  GStreamer auto-downloaded           " GStreamer_AUTO_DOWNLOADED)
OptionOutput("Disable APM MAVLink dialect           " QGC_DISABLE_APM_MAVLINK)
OptionOutput("Disable APM plugin                    " QGC_DISABLE_APM_PLUGIN)
OptionOutput("Disable PX4 plugin                    " QGC_DISABLE_PX4_PLUGIN)
OptionOutput("Enable code coverage                  " QGC_ENABLE_COVERAGE)
OptionOutput("Enable AddressSanitizer               " QGC_ENABLE_ASAN)
OptionOutput("Enable UndefinedBehaviorSanitizer     " QGC_ENABLE_UBSAN)
OptionOutput("Enable ThreadSanitizer                " QGC_ENABLE_TSAN)
OptionOutput("Enable MemorySanitizer                " QGC_ENABLE_MSAN)
OptionOutput("Enable clang-tidy                     " QGC_ENABLE_CLANG_TIDY)
OptionOutput("Warnings as errors                    " QGC_ENABLE_WERROR)
OptionOutput("Security hardening                    " QGC_ENABLE_HARDENING)
OptionOutput("Reproducible build paths              " QGC_REPRODUCIBLE_BUILD)
OptionOutput("Verbose configure output              " QGC_VERBOSE_CONFIGURE)
OptionOutput("Git submodule update                  " GIT_SUBMODULE)

# External Dependencies
message(STATUS "")
message(STATUS "External Dependencies:")
_qgc_kv("MAVLink repo:       " "${QGC_MAVLINK_GIT_REPO}")
_qgc_kv("MAVLink tag:        " "${QGC_MAVLINK_GIT_TAG}")
_qgc_kv("CPM cache:          " "${CPM_SOURCE_CACHE}")
if(QGC_ENABLE_GST_VIDEOSTREAMING AND GStreamer_VERSION)
    _qgc_kv("GStreamer version:  " "${GStreamer_VERSION}")
    _qgc_kv("GStreamer root:     " "${GStreamer_ROOT}")
endif()
if(CMAKE_GENERATOR MATCHES "Ninja")
    _qgc_kv("Link job pool:      " "${QGC_LINK_PARALLEL_LEVEL} parallel jobs")
endif()
_qgc_kv("QML output dir:     " "${QT_QML_OUTPUT_DIRECTORY}")
if(QGC_ENABLE_COVERAGE)
    message(STATUS "  Coverage line min:  ${QGC_COVERAGE_LINE_THRESHOLD}%")
    message(STATUS "  Coverage branch min: ${QGC_COVERAGE_BRANCH_THRESHOLD}%")
endif()
if(VALGRIND_EXECUTABLE)
    message(STATUS "  Valgrind:           ${VALGRIND_EXECUTABLE}")
    message(STATUS "  Valgrind timeout:   ${QGC_VALGRIND_TIMEOUT_MULTIPLIER}x")
endif()

# Platform-Specific Settings
if(ANDROID)
    message(STATUS "")
    message(STATUS "Android Platform:")
    message(STATUS "  Target SDK:         ${QGC_QT_ANDROID_TARGET_SDK_VERSION}")
    message(STATUS "  Min SDK:            ${QGC_QT_ANDROID_MIN_SDK_VERSION}")
    message(STATUS "  NDK host:           ${ANDROID_NDK_HOST_SYSTEM_NAME}")
    message(STATUS "  SDK root:           ${ANDROID_SDK_ROOT}")
    message(STATUS "  Package:            ${QGC_ANDROID_PACKAGE_NAME}")
    message(STATUS "  APK signing:        ${QT_ANDROID_SIGN_APK}")
    message(STATUS "  AAB signing:        ${QT_ANDROID_SIGN_AAB}")
endif()

if(MACOS)
    message(STATUS "")
    message(STATUS "macOS Platform:")
    message(STATUS "  Bundle ID:          ${QGC_MACOS_BUNDLE_ID}")
    message(STATUS "  Deployment target:  ${CMAKE_OSX_DEPLOYMENT_TARGET}")
    if(QGC_MACOS_UNIVERSAL_BUILD)
        message(STATUS "  Architectures:      ${CMAKE_OSX_ARCHITECTURES}")
    endif()
endif()

if(IOS)
    message(STATUS "")
    message(STATUS "iOS Platform:")
    message(STATUS "  Deployment target:  ${QGC_IOS_DEPLOYMENT_TARGET}")
    message(STATUS "  Device family:      ${QGC_IOS_TARGETED_DEVICE_FAMILY}")
endif()

if(WIN32 AND NOT ANDROID)
    message(STATUS "")
    message(STATUS "Windows Platform:")
    message(STATUS "  Icon:               ${QGC_WINDOWS_ICON_PATH}")
    message(STATUS "  Resource file:      ${QGC_WINDOWS_RESOURCE_FILE_PATH}")
endif()

if(LINUX AND NOT ANDROID)
    message(STATUS "")
    message(STATUS "Linux Platform:")
    if(QGC_CREATE_APPIMAGE)
        message(STATUS "  AppImage:           Enabled")
    endif()
endif()

if(QGC_VERBOSE_CONFIGURE)
    message(STATUS "")
    message(STATUS "Verbose Detail:")
    _qgc_kv("Hardening CXX:      " "${QGC_HARDENING_CXX_FLAGS}")
    _qgc_kv("Hardening link:     " "${QGC_HARDENING_LINK_FLAGS}")
    _qgc_kv("CXX Debug flags:    " "${CMAKE_CXX_FLAGS_DEBUG}")
    _qgc_kv("CXX Release flags:  " "${CMAKE_CXX_FLAGS_RELEASE}")
    _qgc_kv("CXX RelWithDeb:     " "${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
    _qgc_kv("Shared link flags:  " "${CMAKE_SHARED_LINKER_FLAGS}")
    _qgc_kv("Module path:        " "${CMAKE_MODULE_PATH}")

    include(FeatureSummary)
    message(STATUS "")
    feature_summary(
        WHAT PACKAGES_FOUND PACKAGES_NOT_FOUND
        INCLUDE_QUIET_PACKAGES
        QUIET_ON_EMPTY
        DESCRIPTION "Dependency Discovery (find_package results):")
endif()

message(STATUS "")
message(STATUS "==================================================================")
message(STATUS "")
