# output chosen build options
macro( OptionOutput _outputstring )
    if( ${ARGN} )
        set( _var "YES" )
    else( ${ARGN} )
        set( _var "NO" )
    endif( ${ARGN} )
    message( STATUS "${_outputstring}${_var}" )
endmacro( OptionOutput _outputstring )

function(printList items)
    foreach (item ${items})
        message("\t ${item}")
    endforeach()
endfunction()

get_property(COMPILER_OPTIONS DIRECTORY ${CMAKE_SOURCE_DIR} PROPERTY COMPILE_OPTIONS)

include(CMakePrintHelpers)
# include(CMakePrintSystemInformation)
# include(ProcessorCount)

message( STATUS "Install prefix:              ${CMAKE_INSTALL_PREFIX}" )
message( STATUS "------------------------------------------------------------------" )
message( STATUS "CMake Generator:             ${CMAKE_GENERATOR}" )
message( STATUS "CMAKE_BUILD_TYPE:            ${CMAKE_BUILD_TYPE}" )
message( STATUS "Compiler info:               ${CMAKE_CXX_COMPILER_ID} (${CMAKE_CXX_COMPILER}) ; version: ${CMAKE_CXX_COMPILER_VERSION}" )
message( STATUS "CMAKE_CXX_STANDARD:          ${CMAKE_CXX_STANDARD}" )
message( STATUS " --- Compiler flags --- ")
message( STATUS "General:                     ${CMAKE_CXX_FLAGS}" )
printList("${COMPILER_OPTIONS}")
message( STATUS "Extra:                       ${EXTRA_COMPILE_FLAGS}" )
message( STATUS "Debug:                       ${CMAKE_CXX_FLAGS_DEBUG}" )
message( STATUS "Release:                     ${CMAKE_CXX_FLAGS_RELEASE}" )
message( STATUS "RelWithDebInfo:              ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}" )
message( STATUS "MinSizeRel:                  ${CMAKE_CXX_FLAGS_MINSIZEREL}" )
message( STATUS " --- Linker flags --- ")
message( STATUS "General:                     ${CMAKE_EXE_LINKER_FLAGS}" )
message( STATUS "Debug:                       ${CMAKE_EXE_LINKER_FLAGS_DEBUG}" )
message( STATUS "Release:                     ${CMAKE_EXE_LINKER_FLAGS_RELEASE}" )
message( STATUS "RelWithDebInfo:              ${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}" )
message( STATUS "MinSizeRel:                  ${CMAKE_EXE_LINKER_FLAGS_MINSIZEREL}" )
message( STATUS "" )

message( STATUS "CMake Version:               ${CMAKE_VERSION}" )
message( STATUS "CMake Prefix:                ${CMAKE_PREFIX_PATH}" )
message( STATUS "CMake Host System Name:      ${CMAKE_HOST_SYSTEM_NAME}" )
message( STATUS "CMake Host System Version:   ${CMAKE_HOST_SYSTEM_VERSION}" )
message( STATUS "CMake System Name:           ${CMAKE_SYSTEM_NAME}" )
message( STATUS "CMake System Version:        ${CMAKE_SYSTEM_VERSION}" )
message( STATUS "CMake Source Dir:            ${CMAKE_SOURCE_DIR}" )
message( STATUS "CMake Toolchain File:        ${CMAKE_TOOLCHAIN_FILE}" )

message( STATUS "App Name:                    ${QGC_APP_NAME}" )
message( STATUS "App Copyright:               ${QGC_APP_COPYRIGHT}" )
message( STATUS "App Description:             ${QGC_APP_DESCRIPTION}" )
message( STATUS "Org Name:                    ${QGC_ORG_NAME}" )
message( STATUS "App Domain:                  ${QGC_ORG_DOMAIN}" )
message( STATUS "App Version:                 ${QGC_APP_VERSION_STR}" )

if(MACOS)
message( STATUS "MacOS Bundle ID:             ${QGC_BUNDLE_ID}" )
message( STATUS "MacOS Icon Path:             ${QGC_MACOS_ICON_PATH}" )
endif()

if(ANDROID)
message( STATUS "Android NDK Host System      ${ANDROID_NDK_HOST_SYSTEM_NAME}" )
message( STATUS "Android SDK Root             ${ANDROID_SDK_ROOT}" )
endif()

OptionOutput( "Stable Build:                " QGC_STABLE_BUILD )
OptionOutput( "Building Tests:              " QGC_BUILD_TESTING AND BUILD_TESTING )
OptionOutput( "Debug QML:                   " QGC_DEBUG_QML )
OptionOutput( "Build Dependencies:          " QGC_BUILD_DEPENDENCIES )

OptionOutput( "Disable APM Dialect:         " QGC_DISABLE_APM_MAVLINK )
OptionOutput( "Disable APM Plugin:          " QGC_DISABLE_APM_PLUGIN )
OptionOutput( "Disable APM Plugin Factory:  " QGC_DISABLE_APM_PLUGIN_FACTORY )

OptionOutput( "Disable PX4 Plugin:          " QGC_DISABLE_PX4_PLUGIN )
OptionOutput( "Disable PX4 Plugin Factory:  " QGC_DISABLE_PX4_PLUGIN_FACTORY )

OptionOutput( "Enable Bluetooth Links:      " QGC_ENABLE_BLUETOOTH )
OptionOutput( "Enable ZeroConf:             " QGC_ZEROCONF_ENABLED )
OptionOutput( "Disable AIRLink:             " QGC_AIRLINK_DISABLED )
OptionOutput( "Disable Serial Links:        " QGC_NO_SERIAL_LINK )

OptionOutput( "Enable UTM Adapter:          " QGC_UTM_ADAPTER )
OptionOutput( "Enable Viewer3D:             " QGC_VIEWER3D )

OptionOutput( "Enable UVC Devices:          " QGC_ENABLE_UVC )
OptionOutput( "Enable GStreamer:            " QGC_ENABLE_GST_VIDEOSTREAMING )
OptionOutput( "Enable QtMultimedia:         " QGC_ENABLE_QT_VIDEOSTREAMING )

message( STATUS "MAVLink Git Repo:            ${QGC_MAVLINK_GIT_REPO}" )
message( STATUS "MAVLink Git Tag:             ${QGC_MAVLINK_GIT_TAG}" )
