qt_add_library(QGCGPSRTCMMAVLink STATIC RTCMMAVLink.cc RTCMMAVLinkPacket.cc)
add_library(QGC::GPSRTCMMAVLink ALIAS QGCGPSRTCMMAVLink)
set_target_properties(QGCGPSRTCMMAVLink PROPERTIES AUTOMOC ON POSITION_INDEPENDENT_CODE ON)
target_compile_features(QGCGPSRTCMMAVLink PUBLIC cxx_std_20)
target_link_libraries(
    QGCGPSRTCMMAVLink
    PUBLIC Qt6::Core QGCIO
    PRIVATE QGCLoggingCategory
)
target_sources(QGCGPSRTCMMAVLink PUBLIC FILE_SET HEADERS FILES RTCMMAVLink.h RTCMMAVLinkPacket.h)
