.\"
.\" Copyright (c) Mark J. Kilgard, 1996.
.\"
.TH glutShowOverlay 3GLUT "3.7" "GLUT" "GLUT"
.SH NAME
glutShowOverlay, glutHideOverlay - shows or hides the overlay of the current window
.SH SYNTAX
.nf
.LP
void glutShowOverlay(void);
void glutHideOverlay(void);
.fi
.SH DESCRIPTION
glutShowOverlay shows the overlay of the current window;  
glutHideOverlay hides the overlay. The effect of showing or
hiding an overlay takes place immediately. Note that
glutShowOverlay will not actually display the overlay unless the
window is also shown (and even a shown window may be obscured
by other windows, thereby obscuring the overlay). It is typically
faster and less resource intensive to use these routines to control the
display status of an overlay as opposed to removing and
re-establishing the overlay. 
.SH SEE ALSO
glutEstablishOverlay, glutShowWindow
.SH AUTHOR
Mark J. Kilgard (mjk@nvidia.com)
