.\"
.\" Copyright (c) Mark J. Kilgard, 1996.
.\"
.TH glutRemoveMenuItem 3GLUT "3.7" "GLUT" "GLUT"
.SH NAME
glutRemoveMenuItem - remove the specified menu item. 
.SH SYNTAX
.nf
.LP
void glutRemoveMenuItem(int entry);
.fi
.SH ARGUMENTS
.IP \fIentry\fP 1i
Index into the menu items of the current menu (1 is the topmost menu item). 
.SH DESCRIPTION
glutRemoveMenuItem remove the entry menu item regardless of
whether it is a menu entry or sub-menu trigger. entry must be between 1
and glutGet(GLUT_MENU_NUM_ITEMS) inclusive. Menu items below
the removed menu item are renumbered. 
.SH SEE ALSO
glutAddMenuEntry, glutAddSubMenu, glutChangeToMenuEntry, glutChangeToSubMenu
.SH AUTHOR
Mark J. Kilgard (mjk@nvidia.com)
