.\"
.\" Copyright (c) Mark J. Kilgard, 1996.
.\"
.TH glutAddMenuEntry 3GLUT "3.7" "GLUT" "GLUT"
.SH NAME
glutAddMenuEntry - adds a menu entry to the bottom of the current menu. 
.SH SYNTAX
.nf
.LP
void glutAddMenuEntry(char *name, int value);
.fi
.SH ARGUMENTS
.IP \fIname\fP 1i
ASCII character string to display in the menu entry. 
.IP \fIvalue\fP 1i
Value to return to the menu's callback function if the menu
entry is selected. 
.SH DESCRIPTION
glutAddMenuEntry adds a menu entry to the bottom of the current
menu. The string name will be displayed for the newly added menu
entry. If the menu entry is selected by the user, the menu's callback
will be called passing value as the callback's parameter. 
.SH SEE ALSO
glutAddSubMenu, glutCreateMenu, glutChangeToMenuEntry, glutRemoveMenuItem
.SH AUTHOR
Mark J. Kilgard (mjk@nvidia.com)
