.\"
.\" Copyright (c) Mark J. Kilgard, 1996.
.\"
.TH glutSolidSphere 3GLUT "3.7" "GLUT" "GLUT"
.SH NAME
glutSolidSphere, glutWireSphere - render a solid or wireframe sphere respectively. 
.SH SYNTAX
.nf
.LP
void glutSolidSphere(GLdouble radius,
                     GLint slices, GLint stacks);
void glutWireSphere(GLdouble radius,
                    GLint slices, GLint stacks);
.fi
.SH ARGUMENTS
.IP \fIradius\fP 1i
The radius of the sphere. 
.IP \fIslices\fP 1i
The number of subdivisions around the Z axis (similar to lines of longitude). 
.IP \fIstacks\fP 1i
The number of subdivisions along the Z axis (similar to lines of latitude). 
.SH DESCRIPTION
Renders a sphere centered at the modeling coordinates origin of the
specified radius. The sphere is subdivided around the Z axis into slices
and along the Z axis into stacks. 
.SH SEE ALSO
glutSolidCube, glutSolidCone, glutSolidTorus, glutSolidDodecahedron,
glutSolidOctahedron, glutSolidTetrahedron, glutSolidIcosahedron,
glutSolidTeapot
.SH AUTHOR
Mark J. Kilgard (mjk@nvidia.com)
