.\"
.\" Copyright (c) Mark J. Kilgard, 1996.
.\"
.TH glutAddSubMenu 3GLUT "3.7" "GLUT" "GLUT"
.SH NAME
glutAddSubMenu - adds a sub-menu trigger to the bottom of the current menu. 
.SH SYNTAX
.nf
.LP
void glutAddSubMenu(char *name, int menu);
.fi
.SH ARGUMENTS
.IP \fIname\fP 1i
ASCII character string to display in the menu item from which
to cascade the sub-menu. 
.IP \fImenu\fP 1i
Identifier of the menu to cascade from this sub-menu menu item. 
.SH DESCRIPTION
glutAddSubMenu adds a sub-menu trigger to the bottom of the
current menu. The string name will be displayed for the newly added
sub-menu trigger. If the sub-menu trigger is entered, the sub-menu
numbered menu will be cascaded, allowing sub-menu menu items to
be selected. 
.SH SEE ALSO
glutAddMenuEntry, glutChangeToSubMenu, glutRemoveItem
.SH AUTHOR
Mark J. Kilgard (mjk@nvidia.com)
