.\"
.\" Copyright (c) Mark J. Kilgard, 1996.
.\"
.TH glutDestroyMenu 3GLUT "3.7" "GLUT" "GLUT"
.SH NAME
glutDestroyMenu - destroys the specified menu. 
.SH SYNTAX
.nf
.LP
void glutDestroyMenu(int menu);
.fi
.SH ARGUMENTS
.IP \fImenu\fP 1i
The identifier of the menu to destroy. 
.SH DESCRIPTION
glutDestroyMenu destroys the specified menu by menu. If menu
was the current menu, the current menu becomes invalid and
glutGetMenu will return zero. 
.SH SEE ALSO
glutCreateMenu, glutDestroyWindow
.SH AUTHOR
Mark J. Kilgard (mjk@nvidia.com)
