.\"
.\" Copyright (c) Mark J. Kilgard, 1996.
.\"
.TH glutSolidDodecahedron 3GLUT "3.7" "GLUT" "GLUT"
.SH NAME
glutSolidDodecahedron, glutWireDodecahedron - render a
solid or wireframe dodecahedron (12-sided regular solid) respectively. 
.SH SYNTAX
.nf
.LP
void glutSolidDodecahedron(void);
void glutWireDodecahedron(void);
.fi
.SH DESCRIPTION
glutSolidDodecahedron and glutWireDodecahedron render a
solid or wireframe dodecahedron respectively centered at the modeling
coordinates origin with a radius of sqrt(3). 
.SH SEE ALSO
glutSolidSphere, glutSolidCube, glutSolidCone, glutSolidTorus,
glutSolidOctahedron, glutSolidTetrahedron, glutSolidIcosahedron,
glutSolidTeapot
.SH AUTHOR
Mark J. Kilgard (mjk@nvidia.com)
