.\"
.\" Copyright (c) Mark J. Kilgard, 1996.
.\"
.TH glutSolidIcosahedron 3GLUT "3.7" "GLUT" "GLUT"
.SH NAME
glutSolidIcosahedron, glutWireIcosahedron - render a
solid or wireframe icosahedron (20-sided regular solid) respectively. 
.SH SYNTAX
.nf
.LP
void glutSolidIcosahedron(void);
void glutWireIcosahedron(void);
.fi
.SH DESCRIPTION
glutSolidIcosahedron and glutWireIcosahedron render a solid
or wireframe icosahedron respectively. The icosahedron is centered at the
modeling coordinates origin and has a radius of 1.0. 
.SH SEE ALSO
glutSolidSphere, glutSolidCube, glutSolidCone, glutSolidTorus, glutSolidDodecahedron,
glutSolidOctahedron, glutSolidTetrahedron,
glutSolidTeapot
.SH AUTHOR
Mark J. Kilgard (mjk@nvidia.com)
