.\"
.\" Copyright (c) Mark J. Kilgard, 1996.
.\"
.TH glutSolidCube 3GLUT "3.7" "GLUT" "GLUT"
.SH NAME
glutSolidCube, glutWireCube - render a solid or wireframe cube respectively. 
.SH SYNTAX
.nf
.LP
void glutSolidCube(GLdouble size);
void glutWireCube(GLdouble size);
.fi
.SH ARGUMENTS
.IP \fIsize\fP 1i
Length of each edge.
.SH DESCRIPTION
glutSolidCube and glutWireCube render a solid or wireframe cube
respectively. The cube is centered at the modeling coordinates origin with
sides of length size. 
.SH SEE ALSO
glutSolidSphere, glutSolidCone, glutSolidTorus, glutSolidDodecahedron,
glutSolidOctahedron, glutSolidTetrahedron, glutSolidIcosahedron,
glutSolidTeapot
.SH AUTHOR
Mark J. Kilgard (mjk@nvidia.com)
