.\"
.\" Copyright (c) Mark J. Kilgard, 1996.
.\"
.TH glutSolidTetrahedron 3GLUT "3.7" "GLUT" "GLUT"
.SH NAME
glutSolidTetrahedron, glutWireTetrahedron - render a
solid or wireframe tetrahedron (4-sided regular solid) respectively. 
.SH SYNTAX
.nf
.LP
void glutSolidTetrahedron(void);
void glutWireTetrahedron(void);
.fi
.SH DESCRIPTION
glutSolidTetrahedron and glutWireTetrahedron render a solid
or wireframe tetrahedron respectively centered at the modeling
coordinates origin with a radius of sqrt(3). 
.SH SEE ALSO
glutSolidSphere, glutSolidCube, glutSolidCone, glutSolidTorus, glutSolidDodecahedron,
glutSolidOctahedron, glutSolidIcosahedron,
glutSolidTeapot
.SH AUTHOR
Mark J. Kilgard (mjk@nvidia.com)
