.\"
.\" Copyright (c) Mark J. Kilgard, 1996.
.\"
.TH glutPopWindow 3GLUT "3.7" "GLUT" "GLUT"
.SH NAME
glutPopWindow, glutPushWindow - change the stacking order of the current window relative to its siblings. 
.SH SYNTAX
.nf
.LP
void glutPopWindow(void);
void glutPushWindow(void);
.fi
.SH DESCRIPTION
glutPopWindow and glutPushWindow work on both top-level
windows and subwindows. The effect of pushing and popping windows
does not take place immediately. Instead the push or pop is saved for
execution upon return to the GLUT event loop. Subsequent push or pop
requests on a window replace the previously saved request for that
window. The effect of pushing and popping top-level windows is subject
to the window system's policy for restacking windows. 
.SH SEE ALSO
glutShowWindow, glutIconifyWindow, glutHideWindow
.SH AUTHOR
Mark J. Kilgard (mjk@nvidia.com)
