name: QGC Multi-Platform Build

on:
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Qt and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-tools-dev cmake ninja-build build-essential

      - name: Build QGroundControl (Linux)
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Qt and MSVC (example)
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.8.3'
          host: win64
          target: desktop

      - name: Build QGroundControl (Windows)
        run: |
          mkdir build
          cd build
          cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

  build-android:
    runs-on: macos-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          ndk-version: 25.2.9519653

      - name: Install Qt for Android
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.8.3'
          host: macos
          target: android

      - name: Build QGroundControl (Android)
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DANDROID=true
          cmake --build . --config Release
