name: clang-format Check
on: [workflow_dispatch]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'test'
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C++ Source Files.
      uses: jidicula/clang-format-action@main
      with:
        clang-format-version: '17'
        check-path: ${{ matrix.path }}
