name: ClusterFuzzLite

on:
  push:
    branches:
      - master
    paths:
      - '.clusterfuzzlite/**'
      - '.github/workflows/clusterfuzzlite.yml'
      - 'cmake/CustomOptions.cmake'
      - 'test/Fuzz/**'
  pull_request:
    paths:
      - '.clusterfuzzlite/**'
      - '.github/workflows/clusterfuzzlite.yml'
      - 'cmake/CustomOptions.cmake'
      - 'test/Fuzz/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  fuzz:
    name: MAVLink Parser (AddressSanitizer)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Build fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c++
          github-token: ${{ secrets.GITHUB_TOKEN }}
          keep-unaffected-fuzz-targets: true
          sanitizer: address

      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: code-change
          sanitizer: address
          output-sarif: true

  continuous-build:
    name: Continuous Fuzzer Build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Build and upload fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c++
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: address
          upload-build: true
