#!/bin/sh
script_dir_path=`dirname $0`
script_dir_path=`(cd "$script_dir_path"; pwd)`

"$script_dir_path/../bin/qt-cmake" -DQT_BUILD_STANDALONE_EXAMPLES=ON -DQT_BUILD_TESTS=OFF -DQT_USE_ORIGINAL_COMPILER=ON "$@"
