QT.svg_private.VERSION = 6.10.3
QT.svg_private.name = QtSvg
QT.svg_private.module =
QT.svg_private.libs = $$QT_MODULE_LIB_BASE
QT.svg_private.includes = $$QT_MODULE_INCLUDE_BASE/QtSvg/6.10.3 $$QT_MODULE_INCLUDE_BASE/QtSvg/6.10.3/QtSvg
QT.svg_private.frameworks = 
QT.svg_private.depends = core_private gui_private svg
QT.svg_private.uses = 
QT.svg_private.module_config = v2 internal_module
QT.svg_private.enabled_features = 
QT.svg_private.disabled_features = 
