QT.help_private.VERSION = 6.10.3
QT.help_private.name = QtHelp
QT.help_private.module =
QT.help_private.libs = $$QT_MODULE_LIB_BASE
QT.help_private.includes = $$QT_MODULE_INCLUDE_BASE/QtHelp/6.10.3 $$QT_MODULE_INCLUDE_BASE/QtHelp/6.10.3/QtHelp
QT.help_private.frameworks = 
QT.help_private.depends = help
QT.help_private.uses = 
QT.help_private.module_config = v2 internal_module
QT.help_private.enabled_features = 
QT.help_private.disabled_features = 
