QT.sql_private.VERSION = 6.10.3
QT.sql_private.name = QtSql
QT.sql_private.module =
QT.sql_private.libs = $$QT_MODULE_LIB_BASE
QT.sql_private.includes = $$QT_MODULE_INCLUDE_BASE/QtSql/6.10.3 $$QT_MODULE_INCLUDE_BASE/QtSql/6.10.3/QtSql
QT.sql_private.frameworks = 
QT.sql_private.depends = core_private sql
QT.sql_private.uses = 
QT.sql_private.module_config = v2 internal_module
QT.sql_private.enabled_features = 
QT.sql_private.disabled_features = 
